(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(local specs ((. (fennel.dofile :extensions/agent.fnl) :setup) {:config {}}))
(local handlers {})
(var register nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler))
  (when (= spec.name :register/agent-delta) (set register spec.handler)))
(fn transition [db event cofx]
  (local before (misa.json.encode db))
  (local input (misa.json.encode event))
  (local result ((. handlers event.type) db event cofx))
  (assert (= before (misa.json.encode db)) "stream handler mutated prior state")
  (assert (= input (misa.json.encode event)) "stream handler mutated event")
  (assert (not (and result result.db)))
  (values (misa.patch db (or (and result result.patch) {})) (or (and result result.fx) [])))
(local initial {:agent {:status :working :active_request_id :request :request_model :model :messages []}})
(local started (transition initial {:type :agent/stream-start :id :request}))
(assert (= (transition started {:type :agent/stream-start :id :request}) started))
(fn delta [db value] (transition db {:type :agent/stream-delta :id :request :delta value}))
(local failure
       (G.for_all (G.vector (G.elements [{:type :text :text :hi} {:type :text :text ""}
                                         {:type :thinking :text :hmm}
                                         {:type :tool_call :index :one :id :call :name :tool :arguments_json ""}
                                         {:type :tool_call :index :one :arguments_json_delta "{}"}
                                         {:type :tool_call :index :one :arguments {:x 1}}]))
                  (fn [deltas]
                    (var db started)
                    (var starts 0)
                    (each [_ value (ipairs deltas)]
                      (local (next effects) (delta db value))
                      (assert (= next.agent.messages initial.agent.messages))
                      (each [_ effect (ipairs effects)]
                        (when (= effect.event.type :transcript/block-start) (set starts (+ starts 1))))
                      (set db next))
                    (assert (= starts (length db.agent.stream.blocks)))
                    (assert (= starts db.agent.stream.block_seq)))
                  {:cases 500 :size 20}))
(assert (not failure) (and failure (fennel.view failure)))
(local text (delta (delta started {:type :text :text :one}) {:type :text :text :two}))
(assert (= (length text.agent.stream.blocks) 1))
(assert (= (table.concat (. text.agent.stream.blocks 1 :chunks)) :onetwo))
(local tool (delta (delta started {:type :tool_call :index :one :id :call :name :tool :arguments_json "{}"})
                   {:type :tool_call :index :one :arguments {}}))
(assert (= (. tool.agent.stream.blocks 1 :arguments_json_chunks) nil))
(assert (= (length tool.agent.stream.blocks) 1))
(local with-usage (transition started {:type :agent/stream-usage :id :request
                                      :usage {:input_tokens 4 :input_includes_cache false}}))
(local more-usage (transition with-usage {:type :agent/stream-usage :id :request :usage {:output_tokens 3}}))
(assert (= more-usage.agent.stream.usage.input_tokens 4))
(assert (= more-usage.agent.stream.usage.input_includes_cache false))
(local state (transition more-usage {:type :agent/stream-state :id :request :provider :test :value {:opaque true}}))
(assert (= (length state.agent.stream.provider_state) 1))
(local observed (transition state {:type :agent/stream-tool-result :id :request :tool_call_id :call :text :done}))
(assert (= (. observed.agent.stream.tool_results :call :role) :tool))
(each [_ type (ipairs [:agent/stream-delta :agent/stream-state :agent/stream-usage :agent/stream-tool-result])]
  (assert (= (transition observed {: type :id :stale}) observed))
  (local cancelled (misa.patch observed {:agent {:cancel_requested true}}))
  (assert (= (transition cancelled {: type :id :request}) cancelled)))
(register {:id :custom :value (fn [_ value] {:patch {:custom value.value}})})
(assert (. (delta started {:type :custom :value true}) :agent :stream :custom))
(local (boot boot-fx) (transition {} {:type :app/start} {:argv [:hello :world]}))
(assert (= (. boot-fx 1 :event :prompt) "hello world"))
(assert boot.agent.exit_after_response)
(local (waiting waiting-fx) (transition {:auth_startup {:ready false}} {:type :app/start} {:argv [:hello]}))
(assert (= waiting.agent.startup_prompt :hello))
(assert (= (length waiting-fx) 0))
(local (released release-fx) (transition waiting {:type :auth/startup-ready}))
(assert (= released.agent.startup_prompt nil))
(assert (= (. release-fx 1 :event :prompt) :hello))
(assert (= (transition released {:type :auth/startup-ready}) released))
(local working (misa.patch boot {:agent {:status :working :active_request_id :request}}))
(local (cancelling cancel-fx) (transition working {:type :agent/cancel-active}))
(assert (= cancelling.agent.status :cancelling))
(assert (= (. cancel-fx 2 :id) :request))
(assert (= (transition cancelling {:type :agent/cancel-active}) cancelling))
(local interrupted (transition (misa.patch text {:agent {:pending_tools {} :cancel_requested true}})
                              {:type :agent/stream-end :id :request}))
(assert (= (. interrupted.agent.messages 1 :content 1 :text) :onetwo))
(assert (= interrupted.agent.stream nil))
(assert (= interrupted.agent.status :ready))
(local (failed failed-fx) (transition working {:type :agent/stream-error :id :request :message :failure}))
(assert (= failed.agent.error :failure))
(assert (= failed.agent.active_request_id nil))
(assert (= (. failed-fx 1 :event :text) :failure))
(local tool-state (misa.patch boot {:agent {:status :tools :accepted_request_id :request
                                          :pending_tool_count 2 :pending_tools {:b true :a true}
                                          :tool_batch {:order [:a :b] :results {}}}}))
(local (_ tool-cancels) (transition tool-state {:type :agent/cancel-active}))
(assert (= (. tool-cancels 2 :id) :a))
(assert (= (. tool-cancels 3 :id) :b))
(local (reset reset-fx) (transition (misa.patch tool-state {:agent {:startup_prompt :queued}})
                                  {:type :agent/reset}))
(assert (= reset.agent.startup_prompt nil) "reset retained a queued startup prompt")
(assert (= reset.agent.request_seq boot.agent.request_seq))
(assert (= (length reset.agent.messages) 0))
(assert (= (next reset.agent.pending_tools) nil))
(assert (= (. reset-fx 1 :id) :a))
(local lifecycle-failure
       (G.for_all (G.vector (G.elements [{:type :agent/cancel-active}
                                         {:type :agent/reset}
                                         {:type :agent/stream-error :id :request :message :failed}
                                         {:type :auth/startup-ready}]))
                  (fn [events]
                    (var db working)
                    (each [_ event (ipairs events)] (set db (transition db event)))
                    (when (= db.agent.status :ready)
                      (assert (= db.agent.active_request_id nil))))
                  {:cases 500 :size 20}))
(assert (not lifecycle-failure) (and lifecycle-failure (fennel.view lifecycle-failure)))
(set misa.tools (fn [] []))
(set misa.tool (fn [name] (when (= name :known) {:effect :tool.test})))
(local available (misa.patch boot {:models {:selected :test :entries [{:id :test :model :test :provider :test}]}}))
(local (submitted submit-fx) (transition available {:type :agent/submit :prompt :hello}))
(assert (= (. submitted.agent.messages 1 :content 1 :text) :hello))
(assert (= (. submit-fx 4 :messages 1 :content 1 :text) :hello)
        "provider effect did not contain the newly submitted message")
(assert (= available.agent.request_seq 0))
(local id submitted.agent.active_request_id)
(local (completed complete-fx) (transition submitted {:type :agent/result : id
                                                     :content [{:type :text :text :answer}]
                                                     :usage {:input_tokens 2 :output_tokens 3}}))
(assert (= completed.agent.status :ready))
(assert (= completed.agent.usage.input_tokens 2))
(assert (= (length completed.agent.messages) 2))
(assert (= (transition completed {:type :agent/result : id :content []}) completed))
(local calls [{:type :tool_call :id :a :name :known :arguments_json "{\"x\":1}"}
              {:type :tool_call :id :b :name :known :arguments {}}])
(local tools (transition submitted {:type :agent/result : id :content calls}))
(assert (= tools.agent.status :tools))
(assert (= (. tools.agent.messages 2 :content 1 :arguments_json) nil))
(assert (= (. tools.agent.messages 2 :content 1 :arguments :x) 1))
(each [_ order (ipairs [[:a :b] [:b :a]])]
  (local first (transition tools {:type :tool/result :tool_call_id (. order 1) :text (. order 1)}))
  (assert (= first.agent.status :tools))
  (assert (= (transition first {:type :tool/result :tool_call_id (. order 1) :text :duplicate}) first))
  (local (next effects) (transition first {:type :tool/result :tool_call_id (. order 2) :text (. order 2)}))
  (assert (= next.agent.status :working))
  (assert (= (. next.agent.messages 3 :tool_call_id) :a))
  (assert (= (. next.agent.messages 4 :tool_call_id) :b))
  (assert (= (. effects 3 :messages 4 :tool_call_id) :b)))
(local cancelling-tools (transition tools {:type :agent/cancel-active}))
(local drained-one (transition cancelling-tools {:type :tool/result :tool_call_id :a}))
(local drained (transition drained-one {:type :tool/result :tool_call_id :b}))
(assert (= drained.agent.status :ready))
(assert (= drained.agent.request_seq tools.agent.request_seq))
(assert (= (. drained.agent.messages 3 :content 1 :text) :Cancelled))
(local unknown (transition submitted {:type :agent/result : id
                                     :content [{:type :tool_call :id :unknown :name :missing :arguments {}}]}))
(assert (= unknown.agent.status :working))
(assert (= (. unknown.agent.messages 3 :is_error) true))
(local provider-owned (transition submitted {:type :agent/result : id
                                            :content [{:type :tool_call :id :owned :name :known
                                                       :execution :provider :arguments {}}]}))
(assert (= provider-owned.agent.status :ready))
(assert (= provider-owned.agent.pending_tool_count 0))
(assert (= (. provider-owned.agent.messages 2 :content 1 :execution) nil))
(set misa.prepare_request_options (fn [] (values nil {:message :blocked})))
(local blocked (transition available {:type :agent/submit :prompt :hello}))
(assert (= (length blocked.agent.messages) 0))
(assert (= blocked.agent.request_seq 0))
(local blocked-continuation (transition (transition tools {:type :tool/result :tool_call_id :a})
                                       {:type :tool/result :tool_call_id :b}))
(assert (= blocked-continuation.agent.status :ready))
(assert (= (length blocked-continuation.agent.messages) 4))
(output "agent stream state properties passed\n")
