(local fennel (require :fennel))
(local output io.write)
(local runtime-debug debug)
(local runtime-os os)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local app ((require :tests.application) {:argv [] :config {}}))
(local declarations (require :misa.definitions))
(app.include (fennel.dofile :extensions/misa/json.fnl) {})
;; Providers register after the auth extension in supported configurations.
(local specs ((fennel.dofile :extensions/misa/providers/auth.fnl) {:config {}}))
(local handlers {})
(each [_ spec (pairs specs.events)]
  (tset handlers spec.event spec.handler)
  nil)
(app.define specs)
(app.define (declarations :auth-state-2 [(let [definition {:id :first :model_provider :model-first :strategy :api_key :discover_models true}] {:catalog :auth-providers :id (. definition :id) :value definition})
                         (let [definition {:id :second :model_provider :model-second :strategy :api_key}] {:catalog :auth-providers :id (. definition :id) :value definition})]))
(app.install)
(assert (= (misa.auth.provider :first) (misa.auth.for-model :model-first)))
(local empty {})
(assert (= empty.auth_startup nil))
(local cofx {:terminal {:interactive true}})
(fn transition [db event]
  (local (before input) (values (misa.json.encode db) (misa.json.encode event)))
  (local result ((. handlers event.type) db event cofx))
  (assert (= before (misa.json.encode db)) "auth handler mutated state")
  (assert (= input (misa.json.encode event)) "auth handler mutated event")
  (assert (not (and result result.db)))
  (values (misa.patch db (or (and result result.patch) {})) (and result result.fx)))
(local (started start-fx) (transition empty {:type :app/start}))
(assert (= empty.auth_startup nil))
(assert started.auth_startup.pending_status.model-first)
(assert started.auth_startup.pending_status.model-second)
(assert (= (transition started {:type :app/start}) started) "startup replaced existing auth progress")
(assert (= (length start-fx) 2))
(assert (= (. start-fx 1 :completion) :auth/provider-status))
(local (_ status-fx) (transition started {:type :auth/status :arguments :first}))
(assert (= (. status-fx 2 :type) :auth/command) "late provider registration was not visible")
(local first (transition started {:type :auth/provider-status :id :model-first :ok true :logged_in true}))
(assert first.auth_startup.pending_discovery.model-first)
(assert (not first.auth_startup.ready))
(assert (= (transition first {:type :auth/provider-status :id :model-first :ok true :logged_in true}) first))
(assert (= (transition first {:type :models/discovery-complete :provider :unrelated}) first))
(local second (transition first {:type :auth/provider-status :id :model-second :ok true :logged_in true}))
(assert (not second.auth_startup.ready))
(local (ready ready-fx) (transition second {:type :models/discovery-complete :provider :model-first}))
(assert ready.auth_startup.ready)
(assert (= (. ready-fx 1 :event :type) :auth/startup-ready))
(assert (= (transition ready {:type :models/discovery-complete :provider :model-first}) ready))
(local early (transition first {:type :models/discovery-complete :provider :model-first}))
(assert (not early.auth_startup.ready))
(assert (. (transition early {:type :auth/provider-status :id :model-second :ok false}) :auth_startup :ready))
(local dialog (misa.patch ready {:dialog {:id :operation}}))
(local preserved (transition dialog {:type :auth/complete :id :other :message :done :ok false}))
(assert (= preserved.dialog dialog.dialog))
(local closed (transition dialog {:type :auth/complete :id :operation :message :done :ok false}))
(assert (= closed.dialog nil))
(assert (= closed.auth_startup dialog.auth_startup))
(local (_ cancel-fx) (transition dialog {:type :auth/dialog-action :cancelled true :id :operation}))
(assert (= (. cancel-fx 1 :type) :operation/cancel))
(assert (= (. cancel-fx 1 :id) :operation))

;; Real queued dispatch must observe all app/start owners regardless of order.
;; Native auth effects are captured only; no provider or auth process is run.
(fn startup-case [order with-providers early-discovery argv]
  ;; A fresh trusted runtime must recapture the host libraries hidden by the previous instance.
  (set _G.debug runtime-debug)
  (set _G.os runtime-os)
  (fennel.dofile :src/lua_runtime/framework.fnl)
  (local app _G.misa)
  (local context {:argv argv :config {}})
  (local scenario ((require :tests.application) context))
  (scenario.include (fennel.dofile :extensions/misa/json.fnl) context)
  (each [_ name (ipairs order)]
    (scenario.include (require name) context))
  (when with-providers
    (scenario.define (declarations :auth-case-604 [(let [definition {:id :fixture :model_provider :fixture :strategy :api_key
                                      :discover_models true}] {:catalog :auth-providers :id (. definition :id) :value definition})
                             (let [definition {:id :second :model_provider :second :strategy :api_key}] {:catalog :auth-providers :id (. definition :id) :value definition})])))
  (var observed nil)
  (local requests [])
  (scenario.define (declarations :auth-case-661 [{:catalog :events  :value {:event :app/start :handler (fn [] {:patch {:models {:selected :fixture/model
                                           :entries [{:id :fixture/model :model :model :provider :fixture}]}}})}}
         {:catalog :events  :value {:event :test/read :handler (fn [db] (set observed db))}}
         {:catalog :effects :id :provider.fixture :value (fn [effect] (table.insert requests effect) [])}]))
  (scenario.install)
  (fn dispatch [event]
    (local pending [event])
    (var at 1)
    (while (. pending at)
      (local fx (app._dispatch (. pending at) {:interactive true :columns 80 :lines 24}
                               {:wall_ms 0 :monotonic_ms 0}))
      (app._commit)
      (each [_ effect (ipairs fx)]
        (when (= effect.type :dispatch) (table.insert pending effect.event)))
      (set at (+ at 1))
      (assert (< at 100) "startup dispatch did not settle"))
    (app._dispatch {:type :test/read} {:interactive true :columns 80 :lines 24}
                   {:wall_ms 0 :monotonic_ms 0})
    (app._commit))
  (dispatch {:type :app/start})
  (local has-auth (accumulate [found false _ name (ipairs order)] (or found (= name :misa.providers.auth))))
  (when (and has-auth with-providers)
    (assert (= (length requests) 0) "startup prompt escaped the auth gate")
    (dispatch {:type :auth/startup-ready})
    (assert (= (length requests) 0) "premature ready event bypassed auth state")
    (dispatch {:type :auth/provider-status :id :fixture :ok true :logged_in true})
    (assert observed.auth_startup.pending_discovery.fixture)
    (if early-discovery
        (dispatch {:type :models/discovery-complete :provider :fixture})
        (dispatch {:type :auth/provider-status :id :second :ok false}))
    (assert (= (length requests) 0) "startup released before both gates completed")
    (if early-discovery
        (dispatch {:type :auth/provider-status :id :second :ok false})
        (dispatch {:type :models/discovery-complete :provider :fixture}))
    (assert observed.auth_startup.ready))
  (local expected (if (> (length argv) 0) 1 0))
  (assert (= (length requests) expected))
  (when (> expected 0)
    (assert (= (. requests 1 :messages 1 :content 1 :text) "hello world")))
  (assert (= observed.agent.startup_prompt nil))
  (dispatch {:type :agent/startup})
  (dispatch {:type :auth/startup-ready})
  (assert (= (length requests) expected) "duplicate continuation submitted twice"))
(each [_ order (ipairs [[:misa.agent :misa.providers.auth] [:misa.providers.auth :misa.agent]])]
  (each [_ early (ipairs [false true])]
    (startup-case order true early [:hello :world]))
  (startup-case order false false [:hello :world])
  (startup-case order true false []))
(startup-case [:misa.agent] false false [:hello :world])
(startup-case [:misa.agent] false false [])
(output "auth state contracts passed\n")
