(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
;; Providers register after the auth extension in supported configurations.
(local specs ((. (fennel.dofile :extensions/auth.fnl) :setup)))
(local handlers {})
(var initialize nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler))
  (when (= spec.type :register/interceptor) (set initialize spec.value.before)))
(misa._setup_effects specs)
(misa._setup_effects {:fx [{:type :register/auth-provider
                          :value {:id :first :model_provider :model-first :strategy :api_key :discover_models true}}
                         {:type :register/auth-provider
                          :value {:id :second :model_provider :model-second :strategy :api_key}}]})
(assert (= (misa.auth_provider :first) (misa.auth_provider_for_model :model-first)))
(local empty {})
(local initialized (initialize {:db empty :event {:type :app/start}}))
(assert (= empty.auth_startup nil))
(local cofx {:terminal {:interactive true}})
(fn transition [db event]
  (local (before input) (values (misa.json.encode db) (misa.json.encode event)))
  (local result ((. handlers event.type) db event cofx))
  (assert (= before (misa.json.encode db)) "auth handler mutated state")
  (assert (= input (misa.json.encode event)) "auth handler mutated event")
  (assert (not (and result result.db)))
  (values (misa.patch db (or (and result result.patch) {})) (and result result.fx)))
(local (started start-fx) (transition initialized.db {:type :app/start}))
(assert (= (length start-fx) 2))
(assert (= (. start-fx 1 :completion) :auth/provider-status))
(local (_ status-fx) (transition started {:type :auth/status :arguments :first}))
(assert (= (. status-fx 2 :type) :auth/command) "late provider registration was not visible")
(local first (transition started {:type :auth/provider-status :id :model-first :ok true :logged_in true}))
(assert first.auth_startup.pending_discovery.model-first)
(assert (not first.auth_startup.ready))
(assert (= (transition first {:type :auth/provider-status :id :model-first :ok true :logged_in true}) first))
(assert (= (transition first {:type :models/discovery-complete :provider :unrelated}) first))
(local second (transition first {:type :auth/provider-status :id :model-second :ok true :logged_in true}))
(assert (not second.auth_startup.ready))
(local (ready ready-fx) (transition second {:type :models/discovery-complete :provider :model-first}))
(assert ready.auth_startup.ready)
(assert (= (. ready-fx 1 :event :type) :auth/startup-ready))
(assert (= (transition ready {:type :models/discovery-complete :provider :model-first}) ready))
(local early (transition first {:type :models/discovery-complete :provider :model-first}))
(assert (not early.auth_startup.ready))
(assert (. (transition early {:type :auth/provider-status :id :model-second :ok false}) :auth_startup :ready))
(local dialog (misa.patch ready {:dialog {:id :operation}}))
(local preserved (transition dialog {:type :auth/complete :id :other :message :done :ok false}))
(assert (= preserved.dialog dialog.dialog))
(local closed (transition dialog {:type :auth/complete :id :operation :message :done :ok false}))
(assert (= closed.dialog nil))
(assert (= closed.auth_startup dialog.auth_startup))
(local (_ cancel-fx) (transition dialog {:type :auth/dialog-action :cancelled true :id :operation}))
(assert (= (. cancel-fx 1 :type) :operation/cancel))
(assert (= (. cancel-fx 1 :id) :operation))
(output "auth state contracts passed\n")
