(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local app ((require :tests.application) {:argv [] :config {}}))
(local definitions (require :tests.declarations))
(local misa _G.misa)
(app.define (. (require :tests.stock) :misa.json))
(local stock (misa.snapshot (. (require :tests.stock) :misa.providers.openai-codex)))
(assert stock.auth-providers.openai-codex.discover_models)
(set stock.auth-providers.openai-codex.discover_models false)
(set stock.models {:fixture/model {:id :fixture/model :model :fixture :provider :openai-codex}})
(app.define stock)
(app.install)
(local feature (fennel.dofile :extensions/misa/providers/openai-codex.fnl))
(local events {:models/discover (fn [db event] (feature.discover-models {} db event))
               :provider/codex-models (fn [db event] (feature.receive-models :openai.responses.codex db event))})
(assert (= ((. events :models/discover) {} {:provider :other}) nil))
(local request (. ((. events :models/discover) {} {:provider :openai-codex}) :fx 1))
(assert (= request.method :GET))
(assert (= request.url "https://chatgpt.com/backend-api/codex/models?client_version=0.153.4"))
(assert (= request.credential.id :openai-codex))
(assert (= request.credential.metadata_header :chatgpt-account-id))
(assert (= request.completion :provider/codex-models))
(local payload {:ok true :data {:models [{:slug :latest :display_name "Latest" :visibility :list
                                        :priority 1 :context_window 200000 :created 1800000000
                                        :recommended true :default_reasoning_level :high
                                        :supported_reasoning_levels [{:effort :medium} {:effort :high}]}
                                       {:slug :hidden :visibility :hide :priority 2}
                                       {:slug :subscription-only :visibility :list :priority 4
                                        :supported_in_api false}]}})
(local before (misa.json.encode payload))
(local completion ((. events :provider/codex-models) {} payload))
(assert (= before (misa.json.encode payload)))
(local replacement (. completion.fx 1 :event))
(assert (= replacement.type :models/replace-provider))
(assert replacement.authoritative)
(assert (= (length replacement.models) 2))
(local latest (. replacement.models 1))
(assert (= latest.id :openai-codex/latest))
(assert (= latest.api.request_options.reasoning_effort.default :high))
(assert (= (. latest.api.request_options.reasoning_effort.choices 1) :medium))
(assert (= latest.recommendation_rank 1))
(assert (= latest.popularity_rank nil))
(assert latest.recommended)
(assert (= latest.created 1800000000))
(assert (= (. replacement.models 2 :model) :subscription-only))
(assert (= (. completion.fx 2 :event :type) :models/discovery-complete))
(each [_ failure (ipairs [{:ok false} {:ok true :data {}} {:ok true :data {:models []}}])]
  (local result ((. events :provider/codex-models) {} failure))
  (assert (= (length result.fx) 1))
  (assert (= (. result.fx 1 :event :type) :models/discovery-complete)))
(assert (= ((. stock.events :provider.openai-codex/discover :handler) {} {:provider :openai-codex}) nil)
        "disabled discovery emitted a request")
(assert (= (length (misa.models.all)) 1))
(assert (= (. (misa.models.all) 1 :id) :fixture/model))
(assert (not (. (misa.auth.for-model :openai-codex) :discover_models)))
(output "Codex model discovery contracts passed\n")
