(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local context {:config {}})
(misa._setup (fennel.dofile :extensions/json.fnl) context)
(misa._setup (fennel.dofile :extensions/preferences.fnl) context)
(local specs ((. (fennel.dofile :extensions/commands.fnl) :setup) context))
(var normalize nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/interceptor) (set normalize spec.value.before)))
(misa._setup_effects specs)
(misa._setup_effects
 {:fx [{:type :register/command
        :value {:name :/choose :description "Choose an option" :event :test/choose
                :completion :options :preference_scope :options}}
       {:type :register/completion :group :options :value {:id :first :value :one}}]})
(local db {:preferences {:clock 0 :scopes {}} :unrelated {:value true}})
(local existing {:type :terminal/read})
(fn transition [event]
  (local input {: db : event :cofx {} :fx [existing]})
  (local before (misa.json.encode input))
  (local result (normalize input))
  (assert (= before (misa.json.encode input)) "normalization mutated input transaction")
  (assert (= result.db.unrelated db.unrelated))
  (assert (= result.cofx input.cofx))
  (assert (= (. result.fx 1) existing))
  (values result input))
(local normalized (transition {:type :test/choose :command :/choose :arguments "  one  "
                               :correlation {:id :retained}}))
(assert (= normalized.event.arguments :one))
(assert (= normalized.event.canonical "/choose one"))
(assert normalized.event.normalized_command)
(assert (= normalized.event.correlation.id :retained))
(assert (= (. normalized.db.preferences.scopes.commands "/choose one" :uses) 1))
(assert (= normalized.db.preferences.scopes.options.first.uses 1))
(assert (= (length normalized.fx) 2))
(assert (= (. normalized.fx 2 :type) :state/save))
(assert (= (misa.json.encode (. normalized.fx 2 :data))
           (misa.json.encode normalized.db.preferences)))
(local opened (transition {:type :test/choose :command :/choose :arguments " "}))
(assert (= opened.event.type :choices/command-open))
(assert (= opened.event.arguments nil))
(assert (= opened.db db))
(assert (= (length opened.fx) 1))
(local resumed (transition {:type :test/choose :command :/choose :arguments " " :resumed_choice true}))
(assert (= resumed.event.type :test/choose))
(assert (= resumed.event.canonical :/choose))
(assert (= (. resumed.db.preferences.scopes.commands :/choose :uses) 1))
(each [_ event (ipairs [{:type :unknown} {:type :unknown :command :/unknown}])]
  (local (result input) (transition event))
  (assert (= result input)))
(output "command transaction ownership passed\n")
