(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local app ((require :tests.application) {:argv [] :config {}}))
(local definitions (require :misa.definitions))
(local misa _G.misa)
(local context {:config {}})
(app.define ((. (fennel.dofile :extensions/misa/json.fnl) :build) context))
(app.define ((. (fennel.dofile :extensions/misa/choices/preferences.fnl) :build) context))
(local specs ((. (fennel.dofile :extensions/misa/commands/init.fnl) :build) context))
(local handlers {})
(each [_ spec (pairs (. specs :events))]
  (tset handlers spec.event spec.handler))
(app.define specs)
(app.define (definitions.build :test [(let [definition {:name :/choose :description "Choose an option" :event :test/choose
                :completion :options :preference_scope :options}] {:catalog :commands :id (. definition :name) :value definition})
       (let [definition {:name :/guarded :description "Unavailable choice" :event :test/guarded
                :completion :options :choice_available (fn [db] db.available)
                :choice_unavailable :test/unavailable}] {:catalog :commands :id (. definition :name) :value definition})
       {:catalog :completions :id (.. :options "/" (. {:id :first :value :one} :value)) :value {:group :options :value {:id :first :value :one}}}]))
(var observed nil)
(var state nil)
(var executions 0)
(app.define (definitions.build :test [{:catalog :events  :value {:event :test/choose :handler (fn [db event]
                   (set observed event)
                   (set state db)
                   (set executions (+ executions 1))
                   nil)}}]))
(app.install)
(local db {:preferences {:clock 0 :scopes {}} :unrelated {:value true}})
(fn transition [event]
  (local before (misa.json.encode {: db : event}))
  (local result (handlers.commands/invoke db event))
  (assert (= before (misa.json.encode {: db : event})) "invocation mutated input")
  (local next (misa.patch db (or result.patch {})))
  (assert (= next.unrelated db.unrelated))
  (values result next))
(local event (misa.patch (misa.commands.invocation "/choose  one  ")
                         {:correlation {:id :retained}}))
(assert (= event.type :commands/invoke))
(local (normalized next) (transition event))
(local execution (. normalized.fx 2 :event))
(assert (= execution.type :test/choose))
(assert (= execution.arguments :one))
(assert (= execution.canonical "/choose one"))
(assert (= execution.correlation event.correlation))
(assert (= (. next.preferences.scopes.commands "/choose one" :uses) 1))
(assert (= next.preferences.scopes.options.first.uses 1))
(assert (= (length normalized.fx) 2))
(assert (= (. normalized.fx 1 :type) :state/save))
(assert (= (misa.json.encode (. normalized.fx 1 :data))
           (misa.json.encode next.preferences)))
(local (opened unchanged) (transition (misa.commands.invocation "/choose")))
(assert (= (. opened.fx 1 :event :type) :choices/command-open))
(assert (= unchanged db))
(local (resumed resumed-db)
       (transition (misa.patch (misa.commands.invocation "/choose") {:resumed_choice true})))
(assert (= (. resumed.fx 2 :event :type) :test/choose))
(assert (= (. resumed-db.preferences.scopes.commands :/choose :uses) 1))
(local guarded (handlers.choices/command-open db {:command :/guarded}))
(assert (= (. guarded.fx 1 :event :type) :test/unavailable))
(assert (= guarded.patch nil))
(assert (= (misa.commands.invocation "/missing") nil))
(assert (not (pcall handlers.commands/invoke db {:command :/missing})))
(fn step [event]
  (local effects (misa._dispatch event {:columns 80 :lines 24 :interactive false}
                                {:wall_ms 0 :monotonic_ms 0}))
  (misa._commit)
  effects)
;; A domain event with command metadata is already an execution, not a request
;; to normalize, count preferences, or open choices again.
(local direct {:type :test/choose :command :/choose :arguments "  direct  "})
(step direct)
(assert (= observed.arguments "  direct  "))
(assert (= state.preferences nil))
(local effects (step (misa.commands.invocation "/choose one")))
(assert (= executions 1) "execution bypassed the event queue")
(each [_ effect (ipairs effects)]
  (when (= effect.type :dispatch) (step effect.event)))
(assert (= executions 2))
(assert (= observed.arguments :one))
(assert (= (. state.preferences.scopes.commands "/choose one" :uses) 1))
(assert (= state.preferences.scopes.options.first.uses 1))
(output "explicit command invocation ownership passed\n")
