(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(set misa.request_option_choices (fn [db] (or db.options [])))
(set misa.request_option_value (fn [db] db.selected))
(set misa.keybinding_action (fn [_ event] event.action))
(local specs {})
(each [_ name (ipairs [:effort :images :queue])]
  (tset specs name ((. (fennel.dofile (.. :extensions/ name :.fnl)) :setup) {:config {}})))
(fn input [name db event]
  (local tx {: db : event :cofx {} :fx []})
  (local before (misa.json.encode tx))
  (var result tx)
  (each [_ spec (ipairs (. specs name :fx))]
    (when (= spec.type :register/interceptor) (set result (spec.value.before result))))
  (assert (= before (misa.json.encode tx)) (.. name " changed its transaction or incoming event"))
  result)
(each [_ name (ipairs [:queue :images])]
  (local db {:queue {:pending :queued :sending false :attachments []}
             :images {:pending {:request true}}})
  (local result (input name db {:type :agent/completed :exit true}))
  (assert result.event.keep_alive)
  (assert result.event.exit)
  (assert (= result.db db))
  (local idle (input name {} {:type :agent/completed}))
  (assert (= idle.event.keep_alive nil)))
(local image-enter (input :images {:images {:pending {:request true}}}
                         {:type :terminal/input :kind :enter :text :secret}))
(assert (= image-enter.event.type :ui/redraw))
(assert (= image-enter.event.text nil))
(assert (= (. (input :effort {} {:type :choices/command-open :command :/effort}) :event :type)
           :effort/unsupported))
(assert (= (. (input :effort {} {:type :terminal/input :action :cycle_effort}) :event :type)
           :effort/cycle))
(local handlers {})
(each [_ spec (ipairs specs.effort.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler)))
(fn event [db type fields]
  (local before (misa.json.encode db))
  (local result ((. handlers type) db (or fields {})))
  (assert (= before (misa.json.encode db)))
  (assert (= result.db nil) "effect-only handler returned state")
  (assert (= result.patch nil))
  result.fx)
(local db {:options [:low :high] :selected :low})
(assert (= (. (event db :effort/cycle) 1 :event :value) :high))
(assert (= (. (event db :effort/select {:arguments " low "}) 1 :event :value) :low))
(assert (= (. (event {} :effort/unsupported) 1 :event :type) :transcript/harness))
(assert (= (. (event {} :effort/cycle) 1 :type) :terminal/read))
(assert (not (pcall event db :effort/select {:arguments :unknown})))
(output "control ownership contracts passed\n")
