(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local app ((require :tests.application) {:argv [] :config {}}))
(local definitions (require :misa.definitions))
(app.define ((. (fennel.dofile :extensions/misa/json.fnl) :build) {}))
(set misa.request-options.choices (fn [db] (or db.options [])))
(set misa.request-options.value (fn [db] db.selected))
(set misa.keybindings.action (fn [_ event] event.action))
(local specs {})
(each [name source (pairs {:effort :misa.models.effort
                           :images :misa.editor.images :queue :misa.editor.queue})]
  (tset specs name ((. (require source) :build) {:config {}})))
(each [_ command (pairs specs.effort.commands)]
  (assert (= command.choice_unavailable :effort/unsupported))
  (assert (not (command.choice_available {})))
  (assert (command.choice_available {:options [:low]})))
(each [_ name (ipairs [:queue :images])]
  (app.define {:subscriptions (. specs name :subscriptions) :services (. specs name :services)}))
(app.install)
(each [_ name (ipairs [:queue :images])]
  (assert (= (. specs name :interceptors) nil) "lifecycle policy must not install middleware")
  (local db {:queue {:pending :queued :sending false :attachments []}
             :images {:pending {:request true}}})
  (local before (misa.json.encode db))
  (local query (. misa.editor.lifecycle name))
  (local result (misa.sub db query))
  (assert result.hold_exit)
  (assert (= (= result.block_draft true) (= name :images)))
  (assert (= before (misa.json.encode db)))
  (assert (not (. (misa.sub {} query) :hold_exit))))
(assert (. (misa.sub {:queue {:pending "" :sending true :attachments []}}
                    misa.editor.lifecycle.queue) :hold_exit))
(assert (. (misa.sub {:queue {:pending "" :sending false :attachments [{}]}}
                    misa.editor.lifecycle.queue) :hold_exit))
(local handlers {})
(each [_ spec (pairs specs.effort.events)] (tset handlers spec.event spec.handler))
(fn event [db type fields]
  (local before (misa.json.encode db))
  (local result ((. handlers type) db (or fields {})))
  (assert (= before (misa.json.encode db)))
  (assert (= result.db nil) "effect-only handler returned state")
  (assert (= result.patch nil))
  result.fx)
(local db {:options [:low :high] :selected :low})
(assert (= (. (event db :effort/cycle) 1 :event :value) :high))
(assert (= (. (event db :effort/select {:arguments " low "}) 1 :event :value) :low))
(assert (= (. (event {} :effort/unsupported) 1 :event :type) :transcript/harness))
(assert (= (. (event {} :effort/cycle) 1 :type) :terminal/read))
(assert (not (pcall event db :effort/select {:arguments :unknown})))
(output "control ownership contracts passed\n")
