(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local specs ((. (fennel.dofile :extensions/costs.fnl) :setup)
              {:config {:costs {:models {:test {:input 2 :output 4}}}}}))
(local handlers {})
(each [_ spec (ipairs specs.fx)]
  (assert (not= spec.type :register/interceptor) "accounting must use explicit event handlers")
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler)))
(fn account [tx]
  (local before (fennel.view tx))
  (local result ((assert (. handlers tx.event.type)) tx.db tx.event))
  (assert (= before (fennel.view tx)) "cost accounting mutated its input")
  (assert (not (and result result.db)) "accounting returned legacy mutable state")
  {:db (misa.patch tx.db (or (and result result.patch) {}))})
(local original {:costs {:responses {:earlier {:model :test :cost {:usd 7}}}}})
(local started (account {:db original
                         :event {:type :transcript/response-start
                                 :response_id :current :model :test}}))
(assert (= original.costs.responses.current nil) "start mutated prior state")
(local finished (account {:db started.db
                          :event {:type :transcript/response-end
                                  :response_id :current :usage {:input_tokens 1000000}}}))
(assert (= started.db.costs.responses.current.cost nil) "completion mutated response")
(assert (= finished.db.costs.responses.current.cost.usd 2))
(assert (= finished.db.costs.responses.earlier original.costs.responses.earlier))
(local interrupted (account {:db finished.db
                             :event {:type :transcript/response-interrupted
                                     :response_id :current}}))
(assert (= finished.db.costs.responses.current.cost.usd 2))
(assert interrupted.db.costs.responses.current.cost.unknown)
(local cleared (account {:db interrupted.db :event {:type :transcript/reset}}))
(assert (= (next cleared.db.costs.responses) nil))
(assert interrupted.db.costs.responses.current)
(misa._setup_effects specs)
(misa._setup (fennel.dofile :extensions/values.fnl) {})
(local scope (misa.subscription_scope))
(local pending-cost (scope.query started.db [:costs/response :current]))
(assert (= pending-cost.type :money))
(assert pending-cost.pending)
(assert (= pending-cost.amount nil))
(assert (= pending-cost.text nil))
(local total (scope.query finished.db [:costs/total]))
(local display (scope.query finished.db [:costs/indicator]))
(local earlier (scope.query finished.db [:costs/response :earlier]))
(assert (= total.usd 9))
(assert (= total.text nil) "numeric accounting depends on presentation")
(assert (= display.type :money))
(assert (= display.amount 9))
(assert (= display.currency :USD))
(assert display.estimated)
(assert (not display.unknown))
(assert (= display.text nil))
(assert (= earlier.type :money))
(assert (= earlier.amount 7))
(assert (= earlier.text nil))
(assert (not earlier.pending))
(fn formatted [fact]
  (table.concat (icollect [_ span (ipairs (misa.render_value fact))] span.text)))
(assert (= (formatted pending-cost) :pending))
(assert (= (formatted (scope.query finished.db [:costs/response :current])) "~$2.00"))
(assert (= (formatted (scope.query interrupted.db [:costs/response :current])) "?"))
(assert pending-cost.pending "later cost update mutated pending fact")
(local mixed-db {:costs {:responses {:mixed {:cost {:usd 1 :estimated true :unknown true}}
                                    :reported {:cost {:usd 0.0123 :estimated false :unknown false}}}}})
(local hovered (misa.patch finished.db {:hover_action :button}))
(assert (= total (scope.query hovered [:costs/total])) "hover recomputed cost total")
(assert (= display (scope.query hovered [:costs/indicator])) "hover recomputed cost fact")
(assert (= earlier (scope.query interrupted.db [:costs/response :earlier]))
        "another response invalidated untouched response projection")
(local changed (scope.query interrupted.db [:costs/total]))
(assert (and (= changed.usd 7) changed.unknown))
(local partial-cost (scope.query interrupted.db [:costs/indicator]))
(assert (= partial-cost.amount 7))
(assert partial-cost.unknown)
(assert (= display.amount 9))
(assert (= total.usd 9) "recomputation mutated retained total")
(local fork (scope.fork))
(assert (= (. (fork.query cleared.db [:costs/total]) :usd) 0))
(fork.close)
(assert (= changed (scope.query interrupted.db [:costs/total]))
        "discarded speculative query replaced committed projection")
(assert (= (scope.query cleared.db [:costs/response :earlier]) nil))
(assert (= (scope.query {} [:costs/response :missing]) nil))
(assert (= (. (scope.query {} [:costs/total]) :responses) 0))
(assert (= (. (scope.query {} [:costs/indicator]) :amount) 0))
(assert (= (formatted (scope.query mixed-db [:costs/response :mixed])) "~$1.00 + ?"))
(assert (= (formatted (scope.query mixed-db [:costs/response :reported])) "$0.0123"))
(scope.close)
(local failure
       (G.for_all
         (G.vector (G.tuple [(G.integer 0 10000) G.boolean G.boolean]))
         (fn [items]
           (local consumer (misa.subscription_scope))
           (var state {:costs {:responses {}}})
           (var sum 0)
           (var estimated false)
           (var unknown false)
           (local retained [])
           (each [index item (ipairs items)]
             (local before (consumer.query state [:costs/total]))
             (table.insert retained {:projection before :usd sum :responses (- index 1)})
             (set sum (+ sum (. item 1)))
             (set estimated (or estimated (. item 2)))
             (set unknown (or unknown (. item 3)))
             (set state (misa.patch state {:costs {:responses
                                                   {(tostring index)
                                                    {:cost {:usd (. item 1)
                                                            :estimated (. item 2)
                                                            :unknown (. item 3)}}}}}))
             (local total (consumer.query state [:costs/total]))
             (assert (and (= total.usd sum) (= total.responses index)
                          (= total.estimated estimated) (= total.unknown unknown))
                     "cost fold disagrees with independent accumulator")
             (assert (= total (consumer.query (misa.patch state {:hover_link :url}) [:costs/total]))
                     "unrelated patch invalidated cost facts")
             (each [_ saved (ipairs retained)]
               (assert (and (= saved.projection.usd saved.usd)
                            (= saved.projection.responses saved.responses))
                       "cost fold mutated a retained result")))
           (consumer.close))
         {:cases 200 :size 20}))
(assert (not failure) (and failure (fennel.view failure)))
(output "cost state contracts passed\n")
