(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local context {:argv [] :config {}})
(each [_ name (ipairs [:json :keybindings :actions :layout :commands :choices])]
  (misa._setup (fennel.dofile (.. :extensions/ name :.fnl)) context))
(local handlers {})
(var policy nil)
(each [_ name (ipairs [:editor :editing])]
  (local specs ((. (fennel.dofile (.. :extensions/ name :.fnl)) :setup) context))
  (each [_ spec (ipairs specs.fx)]
    (when (= spec.type :register/event)
      (when (not (. handlers spec.name)) (tset handlers spec.name {}))
      (table.insert (. handlers spec.name) spec.handler))
    (when (= spec.type :register/interceptor) (set policy spec.value)))
  (misa._setup_effects specs))
(local cofx {:argv [] :terminal {:interactive true :columns 80 :lines 24}})
(fn unchanged [db call]
  (local before (misa.json.encode db))
  (local result (call))
  (assert (= before (misa.json.encode db)) "editing mutated prior state")
  result)
(fn transition [db event]
  (local before (misa.json.encode event))
  (local tx (unchanged db #(policy.before {: db : event : cofx :fx {}})))
  (each [_ handler (ipairs (or (. handlers tx.event.type) {}))]
    (local result (unchanged tx.db #(handler tx.db tx.event cofx)))
    (when result
      (assert (not result.db))
      (set tx.db (misa.patch tx.db (or result.patch {})))
      (each [_ effect (ipairs (or result.fx {}))] (table.insert tx.fx effect))))
  (unchanged tx.db #(policy.after tx))
  (assert (= before (misa.json.encode event)) "editing mutated the input event")
  (values tx.db tx.fx))
(fn action [db name] (transition db {:type :editing/action :action name}))
(local initial {:editor {:text "one two\nthree" :cursor 0 :mode :normal :busy false}
                :editing {}})
(local failure
       (G.for_all (G.vector (G.elements [:left :right :up :down :line_start :line_end
                                         :word_next :word_previous :word_end :first :last
                                         :visual :visual_line :delete :change :yank
                                         :delete_character :paste :undo :redo :normal
                                         :insert :append :insert_start :append_end
                                         :open_above :open_below]))
                  (fn [events]
                    (var db initial)
                    (each [_ name (ipairs events)]
                      (local previous db)
                      (set db (action db name))
                      (local editor db.editor)
                      (assert (and (>= editor.cursor 0) (<= editor.cursor (length editor.text))))
                      (assert (= editor.cursor (misa.layout.boundary_at_or_before editor.text editor.cursor)))
                      (assert (<= (length (or db.editing.undo {})) 64))
                      (assert (<= (length (or db.editing.redo {})) 64))
                      (when editor.selection_start
                        (assert (and (<= editor.selection_start editor.selection_end)
                                     (<= editor.selection_end (length editor.text)))))
                      (when (and (not= name :undo) (not= name :redo)
                                 (not= editor.text previous.editor.text))
                        (local remembered (. db.editing.undo (length db.editing.undo)))
                        (assert (= remembered.text previous.editor.text))
                        (assert (= remembered.cursor previous.editor.cursor)))))
                  {:cases 1000 :size 30}))
(assert (not failure) (and failure (fennel.view failure)))
(local deleted (action initial :delete_character))
(assert (= deleted.editor.text "ne two\nthree"))
(local undone (action deleted :undo))
(assert (= undone.editor.text initial.editor.text))
(local redone (action undone :redo))
(assert (= redone.editor.text deleted.editor.text))
(assert (= redone.editor.cursor deleted.editor.cursor))
(local modified (action undone :open_below))
(assert (= (length modified.editing.redo) 0) "new edit retained a redo branch")
(local empty {:editor {:text "" :cursor 0 :mode :insert} :editing {}})
(local typed (transition empty {:type :terminal/input :kind :text :text :one}))
(local more (transition typed {:type :terminal/input :kind :text :text :two}))
(assert (= (length more.editing.undo) 1) "insert group split into per-event undo entries")
(local normal (transition more {:type :terminal/input :kind :escape}))
(assert (= (. (action normal :undo) :editor :text) ""))
(local cleared (transition more {:type :terminal/input :kind :ctrl_c}))
(assert (= (length cleared.editing.undo) 0))
(assert (= cleared.editing.insert_group nil))
(local restored (transition more {:type :editor/restore :replace true :text :restored}))
(assert (= (length restored.editing.undo) 0))
(local visual (action initial :visual))
(local busy (misa.patch visual {:editor {:busy true}}))
(local escaped (transition busy {:type :terminal/input :kind :ctrl_c}))
(assert (= escaped.editor.text initial.editor.text))
(assert (= escaped.editor.selection_start nil))
(assert (= escaped.editing.anchor nil))
(local pending (action initial :delete))
(local (word-deleted word-fx) (action pending :word_next))
(assert (= word-deleted.editor.text "two\nthree"))
(assert (= (. word-fx 2 :event :text) "one "))
(assert (= word-deleted.editing.operator nil))
(local (line-deleted line-fx) (action pending :delete))
(assert (= line-deleted.editor.text :three))
(assert (= (. line-fx 2 :event :linewise) true))
(local (yanked yank-fx) (action (action visual :right) :yank))
(assert (= yanked.editor.text initial.editor.text))
(assert (= (. yank-fx 2 :event :text) :on))
(assert (= (length (or yanked.editing.undo {})) 0))
(local pasted (action (misa.patch initial {:clipboard {:text "!"}}) :paste))
(assert (= pasted.editor.text "o!ne two\nthree"))
(local line-pasted (action (misa.patch initial {:clipboard {:text "pasted\n" :linewise true}}) :paste))
(assert (= line-pasted.editor.text "one two\npasted\nthree"))
(local unicode (misa.patch initial {:editor {:text "é🙂 x"}}))
(assert (= (. (action unicode :right) :editor :cursor) 3))
(assert (= (. (action unicode :delete_character) :editor :text) "🙂 x"))
;; A choice may consume a text event and clear the draft in the same transition.
;; Clearing that draft must win over insert-group accounting for the text event.
(local consumed (misa.patch more {:editor {:text "" :cursor 0}}))
(local accounted (unchanged consumed
                            #(policy.after {:db consumed :event {:type :terminal/input}
                                            :editing_input {:kind :text :text more.editor.text}
                                            :editing_before {:text more.editor.text :cursor more.editor.cursor}})))
(assert (= (length accounted.db.editing.undo) 0))
(var bounded initial)
(for [_ 1 80] (set bounded (action bounded :open_below)))
(assert (= (length bounded.editing.undo) 64))
(misa._setup_effects {:fx [{:type :register/editing-motion :id :custom_motion :value (fn [] 2)}
                          {:type :register/editing-action :id :custom_action
                           :value (fn [] {:editor {:text :custom :cursor 0}})}]})
(assert (= (. (action initial :custom_motion) :editor :cursor) 2))
(assert (= (. (action initial :custom_action) :editor :text) :custom))
(output "editing state properties passed\n")
