(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local definitions (require :misa.definitions))
(local tool-effect {:type :fixture/run :name :fixture :tool_call_id :call :arguments {}})
(local policy (definitions.build :test [(let [definition {:name :fixture :description :Fixture
                                    :input_schema {:type :object} :effect :fixture/run}] {:catalog :tools :id (. definition :name) :value definition})
       {:catalog :coeffects :id :fixture :value (fn [cofx] (assert (= cofx.clock.wall_ms 123)) :injected)}
       {:catalog :events  :value {:event :fixture/run :handler (fn [] {:fx [tool-effect]})}}
       {:catalog :effects :id :fixture/run :value (fn [effect cofx]
                   (assert (= cofx.fixture :injected))
                   (assert (= cofx.terminal.interactive false))
                   (assert (not effect.arguments.fail) "invalid fixture argument")
                   {:type :dispatch :event {:type :tool/result :tool_call_id effect.tool_call_id :text :done}})}
       {:catalog :serializers :id :fixture :value {:accepts (fn [name] (= name :effort))
                     :serialize (fn [_ value] {:reasoning {:effort value}})}}]))
(misa._install (. (misa.compose [{:definitions ((. (fennel.dofile :extensions/misa/json.fnl) :build) {})} {:definitions policy}]) :definitions) {:argv [] :config {}})
(local terminal {:interactive false :columns 80 :lines 24})
(local clock {:wall_ms 123 :monotonic_ms 456})
(local fx (misa._dispatch {:type :fixture/run} terminal clock))
(misa._commit)
(local mcp (misa._mcp_tool_effect :fixture {} :call terminal clock))
(assert (= (misa.json.encode (. fx 1)) (misa.json.encode mcp))
        "MCP bypassed registered effect/coeffect policy")
(local failure (misa._mcp_tool_effect :fixture {:fail true} :call terminal clock))
(assert (= failure.event.type :tool/result))
(assert failure.event.is_error)
(assert (failure.event.text:find "invalid fixture argument" 1 true))
(local target {:model :fixture :reasoning {:summary :auto}})
(local before (misa.json.encode target))
(local result (misa.request-options.serialize :fixture {:effort :high} target))
(assert (= (misa.json.encode target) before) "serializer changed the caller's request")
(assert (= result.reasoning.effort :high))
(assert (= result.reasoning.summary :auto))
(assert (not (pcall misa.request-options.serialize :fixture {:unknown true} target)))
(output "effect policy contracts passed\n")
