(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(local config {:providers {:fake {:responses [:hello
                                              {:stream [{:type :tool_call :id :call :name :test :arguments {}}
                                                        {:type :tool_call :index 7 :arguments_json :fragment}]
                                               :usage {:output_tokens 3}}
                                              {:stream [] :error :failed}]}}})
(local specs ((. (fennel.dofile :extensions/provider/fake.fnl) :setup) {: config}))
(var handler nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (set handler spec.handler)))
(local fixture (misa.json.encode config))
(fn request [db id]
  (local before (misa.json.encode db))
  (local result (handler db {: id}))
  (assert (= before (misa.json.encode db)) "fake provider mutated prior state")
  (assert (= fixture (misa.json.encode config)) "fake provider mutated configured responses")
  (assert (not result.db))
  (values (misa.patch db result.patch) result.fx))
(local original {:providers {:other {:pending :request}}})
(local (first first-fx) (request original :first))
(assert (= original.providers.fake nil))
(assert (= first.providers.other original.providers.other))
(assert (= first.providers.fake.next_response 2))
(assert (= (. first-fx 1 :event :type) :agent/stream-start))
(assert (= (. first-fx 2 :event :delta :text) :hello))
(assert (= (. first-fx 3 :event :type) :agent/stream-end))
(local (second tool-fx) (request first :second))
(assert (= first.providers.fake.next_response 2))
(assert (= (. tool-fx 2 :event :delta :index) 1))
(assert (= (. tool-fx 3 :event :delta :index) 7))
(assert (= (. tool-fx 4 :event :usage :output_tokens) 3))
(local (third failure-fx) (request second :third))
(assert (= (. failure-fx 2 :event :type) :agent/stream-error))
(assert (= (. failure-fx 2 :event :message) :failed))
(local (exhausted exhausted-fx) (request third :fourth))
(assert (= exhausted.providers.fake.next_response 5))
(assert (= (length exhausted-fx) 1))
(assert (= (. exhausted-fx 1 :event :message) "fake responses exhausted"))
(local replay (request original :replay))
(assert (= (misa.json.encode replay) (misa.json.encode first)) "prior state could not be replayed")
(output "fake provider state contracts passed\n")
