(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local specs ((. (fennel.dofile :extensions/tool/files.fnl) :setup)))
(local handlers {})
(each [_ spec (ipairs specs.fx)]
  (when (or (= spec.type :register/fx) (= spec.type :register/event)) (tset handlers spec.name spec.handler)))
(local failure ((. handlers :tool/files-complete) {} {:id :read :ok false :message :IsDir}))
(assert (: (. failure.fx 1 :event :text) :find "Use list_directory" 1 true))
(assert (: (. failure.fx 1 :event :text) :find "Details: IsDir" 1 true))
(local fallback ((. handlers :tool/files-complete) {} {:id :read :ok false :message :UnknownFailure}))
(assert (= (. fallback.fx 1 :event :text) :UnknownFailure))
(fn edit [arguments] ((. handlers :tool.files/edit) {:tool_call_id :call : arguments}))
(local read ((. handlers :tool.files/read) {:tool_call_id :read :arguments {:path :file}}))
(assert read.anchored)
(local page ((. handlers :tool.files/read) {:tool_call_id :read :arguments {:path :file :start_line 2001 :max_lines 10}}))
(assert (= page.start_line 2001))
(assert (= page.max_lines 10))
(each [_ invalid (ipairs [0 -1 2001 1.5 "10"])]
  (assert (not (pcall (. handlers :tool.files/read) {:tool_call_id :read :arguments {:path :file :max_lines invalid}}))))
(local anchored (edit {:path :file :snapshot :tag :start :1#HASH :new_text :replacement}))
(assert (= anchored.type :file/edit_lines))
(assert (= anchored.content :replacement))
(assert (= anchored.id :call))
(assert (not (pcall edit {:path :file :old_text :old :new_text :new})))
(each [_ spec (ipairs specs.fx)]
  (when (and (= spec.type :register/tool) (= spec.value.name :edit_file))
    (assert (= spec.value.input_schema.properties.old_text nil))
    (assert (= (length spec.value.input_schema.required) 4))))
(assert (not (pcall edit {:path :file :old_text :old :snapshot :tag :new_text :new})))
(assert (not (pcall edit {:path :file :new_text :new})))
(assert (not (pcall edit {:path :file :snapshot :tag :start :1#HASH :end 1 :new_text :new})))
(local shell-specs ((. (fennel.dofile :extensions/tool/shell.fnl) :setup) {:config {}}))
(each [_ spec (ipairs shell-specs.fx)]
  (when (= spec.name :tool/shell-complete)
    (local failed (spec.handler {} {:id :shell :ok false :status 2 :stderr "bad input"}))
    (assert (= (. failed.fx 1 :event :text) "Command exited with status 2.\nbad input"))
    (local timeout (spec.handler {} {:id :shell :ok false :status -1 :message :IdleTimeout}))
    (assert (: (. timeout.fx 1 :event :text) :find "timed out" 1 true))))
(output "file tool contracts passed\n")
