(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local context {:argv [] :config {}})
(local initializers [])
(local app ((require :tests.application) {:argv [] :config {}}))
(local declarations (require :misa.definitions))
(each [_ name (ipairs [:misa.json :misa.ui.themes :misa.ui.themes.default :misa.ui.components :misa.ui.animations
                       :misa.ui.animations.default :misa.providers.auth :misa.agent.models])]
  (local specs ((require name) context))
  (each [_ spec (pairs (or specs.events {}))]

    (when (and true (= spec.event :app/start))
      (table.insert initializers {:id name :handler spec.handler})))
  (app.define specs))
(app.install)
(assert (= (length initializers) 5))
(local initial {:unrelated {:value true}})
(var db initial)
(each [_ policy (ipairs initializers)]
  (local before (misa.json.encode db))
  (local result (policy.handler db {:type :app/start} context))
  (assert (= before (misa.json.encode db)) (.. policy.id " mutated input state"))
  (set db (misa.patch db (or (and result result.patch) {})))
  (assert (= db.unrelated initial.unrelated))
  (local repeated (policy.handler db {:type :app/start} context))
  (assert (= (misa.patch db (or (and repeated repeated.patch) {})) db)
          (.. policy.id " reinitialized existing state")))
(assert (= initial.themes nil))
(assert (= db.themes.active :default))
(assert db.components.roles)
(assert (= db.animations.active :default))
(assert db.auth_startup.ready)
(assert db.models.entries)
(output "initialization transaction ownership passed\n")
