(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(set misa.protocols {:anthropic (fn [] {:fx []})})
(local feature (fennel.dofile :extensions/provider/kimi.fnl))
(fn handlers-for [region]
  (local result {})
  (each [_ spec (ipairs (. (feature.setup {:config {:providers {:kimi {: region}}}}) :fx))]
    (when (= spec.type :register/event) (tset result spec.name spec.handler)))
  result)
(local handlers (handlers-for :global))
(fn apply [db event]
  (local before (misa.json.encode db))
  (local result ((. handlers event.type) db event))
  (assert (= before (misa.json.encode db)) "usage handler mutated state")
  (values (misa.patch db (or (and result result.patch) {})) (or (and result result.fx) [])))
(local (pending requests) (apply {} {:type :usage/refresh}))
(local request (. requests 1))
(assert (= request.url "https://api.kimi.ai/coding/v1/usages"))
(assert (= request.method :GET))
(assert (= request.credential.id :kimi-coding))
(assert (= request.credential.prefix "Bearer "))
(assert (= request.response_format :json))
(assert (= request.headers nil) "request exposed a bearer value")
(local untouched {})
(assert (= (apply untouched {:type :usage/refresh :provider :other}) untouched)
        "unrelated provider refresh changed Kimi state")
(local mainland ((. (handlers-for :mainland) :usage/refresh) {} {}))
(assert (= (. mainland.fx 1 :url) "https://api.kimi.com/coding/v1/usages"))
(local (queued no-requests) (apply pending {:type :usage/refresh}))
(assert queued.providers.kimi.usage_again)
(assert (= (length no-requests) 0) "refresh overlapped an in-flight request")
(assert (= queued (apply queued {:type :usage/refresh})) "repeated refresh changed queued state")
(local (settled followup) (apply queued {:type :provider/kimi-usage :id request.id :ok true
                                        :data {:usage {:limit 100 :used 10}}}))
(assert (= (length followup) 2))
(assert (= (. followup 2 :event :type) :usage/refresh))
(assert (= (. followup 2 :event :provider) :kimi))
(assert (= settled.providers.kimi.usage_again nil))
(local (newer new-requests) (apply settled (. followup 2 :event)))
(assert (not= (. new-requests 1 :id) request.id))
(assert (= newer (apply newer {:type :provider/kimi-usage :id request.id :ok true
                               :data {:usage {:limit 100 :used 10}}}))
        "late completion replaced current usage")
(local (ready effects) (apply pending {:type :provider/kimi-usage :id request.id :ok true
                                      :data {:usage {:limit "100" :remaining "75" :resetAt "2026-09-08T00:00:00Z"}
                                             :limits [{:name "5h" :detail {:limit 20 :used 0}}]}}))
(local windows ready.providers.kimi.usage.windows)
(assert (= (length windows) 2))
(assert (= (. windows 1 :used) 25))
(assert (= (. windows 1 :remaining) 75))
(assert (= (. windows 2 :remaining) 20))
(assert (= (. windows 2 :used) 0))
(assert (= (. effects 1 :event :type) :usage/updated))
(assert (= ready.providers.kimi.usage_request nil))
(assert (= ready (apply ready {:type :provider/kimi-usage :id request.id :ok false})))
(local failed (apply pending {:type :provider/kimi-usage :id request.id :ok false
                              :data {:secret :discarded}}))
(assert failed.providers.kimi.usage.unavailable)
(assert (= (length failed.providers.kimi.usage.windows) 0))
(local (failed-queued retry) (apply queued {:type :provider/kimi-usage :id request.id :ok false}))
(assert failed-queued.providers.kimi.usage.unavailable)
(assert (= (. retry 2 :event :type) :usage/refresh) "failure dropped a queued refresh")
(local (refreshing refresh-requests) (apply ready {:type :usage/refresh}))
(local no-stale (apply refreshing {:type :provider/kimi-usage :id (. refresh-requests 1 :id) :ok false}))
(assert (= (length no-stale.providers.kimi.usage.windows) 0)
        "failed refresh left old quota displayed as current")
(local malformed (apply pending {:type :provider/kimi-usage :id request.id :ok true
                                 :data {:usage {:limit -1 :used "nonsense" :name {}}
                                        :limits [false {:detail {:remaining 0 :name {}}}]}}))
(assert (= (length malformed.providers.kimi.usage.windows) 1))
(assert (= (. malformed.providers.kimi.usage.windows 1 :remaining) 0))
(output "Kimi usage contracts passed\n")
