(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(each [_ name (ipairs [:json :layout])]
  (misa._setup (fennel.dofile (.. :extensions/ name :.fnl)) {}))
(misa._setup (fennel.dofile :extensions/indicators.fnl) {:config {}})
(local specs ((. (fennel.dofile :extensions/models.fnl) :setup) {:config {}}))
(local handlers {})
(var input nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler))
  (when (and (= spec.type :register/interceptor) (= spec.value.id :models/input))
    (set input spec.value.before)))
(misa._setup_effects specs)
(local state {:models {:selected :test :configured_default :test
                       :entries [{:id :test :provider :provider :model :model :context_window 100}]}})
(local selected (misa.selected_model_projection state))
(local projection (misa.models_projection state))
(local unrelated (misa.patch state {:agent {:status :streaming} :models {:available {:other false}}}))
(assert (= selected (misa.selected_model_projection unrelated)))
(assert (= projection (misa.models_projection unrelated)))
(local changed-default (misa.patch state {:models {:configured_default :other}}))
(assert (= selected (misa.selected_model_projection changed-default)))
(assert (= (. (misa.models_projection changed-default) :configured_default) :other))
(assert (= (misa.selected_model_projection (misa.patch state {:models {:selected misa.delete}})) nil))
(assert (= (. (misa.selected_model_projection state) :id) :test))
(local shared-cost {:summary :cost :lines ["Shared cost detail"]})
(set misa.model_cost_info (fn [] shared-cost))
(local complete (. (misa.command :/model) :complete))
(local first (complete "" state))
(local second (complete "" state))
(assert (= (length shared-cost.lines) 1) "model completion mutated shared cost data")
(assert (= (misa.json.encode first) (misa.json.encode second)))
(assert (= (. first 1 :preview :lines 1) "Context: 100 tokens"))
(set misa.keybinding_action (fn [] :open_model_picker))
(local tx {:db {} :event {:type :terminal/input :kind :m :alt true} :fx [] :cofx {}})
(local before (misa.json.encode tx))
(assert (= (. (input tx) :event :type) :model/picker-open))
(assert (= before (misa.json.encode tx)))
(local open ((. handlers :model/picker-open) {}))
(assert (= open.db nil))
(assert (= (. open.fx 1 :event :command) :/model))
(local blocked ((. handlers :model/picker-open) {:dialog {}}))
(assert (= blocked.db nil))
(assert (= (. blocked.fx 1 :type) :terminal/read))
(set misa.keybinding_hint (fn [] :Alt-M))
(var semantic nil)
(set misa.render_component (fn [_ _ model] (set semantic model) {:lines []}))
(misa.indicators_projection {:models {:selected :test :entries [{:id :test :provider :provider :model :model}]}} {})
(local model (. semantic.indicators 1))
(assert (= model.label :model))
(assert (= model.representation :value))
(assert (= model.value :provider/model))
(assert (= model.hotkey :Alt-M))
(local component ((. (fennel.dofile :extensions/component/status.fnl) :setup)))
(local render (. component.fx 1 :value :render))
(local key-spans [{:text :Alt-M}])
(set misa.render_keybinding (fn [] key-spans))
(fn text [view]
  (table.concat (icollect [_ line (ipairs view.lines)]
                 (table.concat (icollect [_ span (ipairs line.spans)] span.text)))))
(local sample {:label :model :value :test :representation :value :hotkey :Alt-M :action :models.open})
(local view (render {:indicators [sample]} {:columns 10}))
(assert (= (text view) "test Alt-M") "value-only width included the hidden label")
(assert (= (. key-spans 1 :action) nil) "status mutated shared keybinding spans")
(assert (= (text (render {:indicators [{:label "◆" :value :test :representation :icon}]} {:columns 6})) "◆ test"))
(assert (= (text (render {:indicators [{:label :model :value :test :representation :label}]} {:columns 10})) "model test"))
(output "model affordance contracts passed\n")
