(local fennel (require :fennel))
(local output io.write)
(local default-file (assert (io.open :config/default.json :rb)))
(local default-source (default-file:read :*a))
(default-file:close)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(each [_ name (ipairs [:json :layout :values])]
  (misa._setup (fennel.dofile (.. :extensions/ name :.fnl)) {}))
(misa._setup (fennel.dofile :extensions/indicators.fnl) {:config {}})
(local specs ((. (fennel.dofile :extensions/models.fnl) :setup) {:config {}}))
(local handlers {})
(var input nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler))
  (when (and (= spec.type :register/interceptor) (= spec.value.id :models/input))
    (set input spec.value.before)))
(misa._setup_effects specs)
(local default-config (misa.json.decode default-source))
(var default-model nil)
(each [_ item (ipairs default-config.config.status.indicators)]
  (when (= item.id :model) (set default-model item)))
(assert (and default-model (= default-model.representation :value) default-model.hotkey)
        "installed default profile does not show model value and binding")
(local state {:models {:selected :test :configured_default :test
                       :entries [{:id :test :provider :provider :model :model :context_window 100}]}})
(local selected (misa.selected_model_projection state))
(assert (= selected.provider :provider))
(local projection (misa.models_projection state))
(local unrelated (misa.patch state {:agent {:status :streaming} :models {:available {:other false}}}))
(assert (= selected (misa.selected_model_projection unrelated)))
(assert (= projection (misa.models_projection unrelated)))
(local changed-default (misa.patch state {:models {:configured_default :other}}))
(assert (= selected (misa.selected_model_projection changed-default)))
(assert (= (. (misa.models_projection changed-default) :configured_default) :other))
(assert (= (misa.selected_model_projection (misa.patch state {:models {:selected misa.delete}})) nil))
(assert (= (. (misa.selected_model_projection state) :id) :test))
(local shared-cost {:currency :USD :token_unit 1000000 :pricing {:input 2 :output 8}})
(set misa.model_cost_info (fn [] shared-cost))
(local complete (. (misa.command :/model) :complete))
(local first (complete "" state))
(local second (complete "" state))
(assert (= shared-cost.pricing.input 2) "model completion mutated shared cost data")
(assert (= (misa.json.encode first) (misa.json.encode second)))
(assert (= (. first 1 :preview :type) :model))
(assert (= (. first 1 :preview :context_window) 100))
(assert (= (. first 1 :preview :cost) shared-cost))
(assert (= (. first 1 :preview :lines) nil) "model owner formatted preview text")
(set misa.keybinding_action (fn [] :open_model_picker))
(local tx {:db {} :event {:type :terminal/input :kind :m :alt true} :fx [] :cofx {}})
(local before (misa.json.encode tx))
(assert (= (. (input tx) :event :type) :model/picker-open))
(assert (= before (misa.json.encode tx)))
(local open ((. handlers :model/picker-open) {}))
(assert (= open.db nil))
(assert (= (. open.fx 1 :event :command) :/model))
(local blocked ((. handlers :model/picker-open) {:dialog {}}))
(assert (= blocked.db nil))
(assert (= (. blocked.fx 1 :type) :terminal/read))
(set misa.keybinding_hint (fn [] :Alt-M))
(var semantic nil)
(set misa.render_component (fn [_ _ model] (set semantic model) {:lines []}))
(misa.indicators_projection {:models {:selected :test :entries [{:id :test :provider :provider :model :model}]}} {})
(local model (. semantic.indicators 1))
(assert (= model.label :model))
(assert (= model.representation :value))
(assert (= model.fact.type :text))
(assert (= model.fact.value :provider/model))
(assert (= model.hotkey :Alt-M))
(local component ((. (fennel.dofile :extensions/component/status.fnl) :setup)))
(var render nil)
(each [_ effect (ipairs component.fx)]
  (when (= effect.type :register/component)
    (assert (= effect.id :default.status.indicators) "parallel status renderer")
    (set render effect.value.render)))
(misa._setup_effects {:fx (icollect [_ effect (ipairs component.fx)]
                           (when (not= effect.type :register/component) effect))})
(local key-spans [{:text :Alt-M}])
(set misa.render_keybinding (fn [] key-spans))
(fn text [view]
  (table.concat (icollect [_ line (ipairs view.lines)]
                 (table.concat (icollect [_ span (ipairs line.spans)] span.text)))))
(local sample {:label :model :fact {:type :text :value :test} :representation :value :hotkey :Alt-M :action :models.open})
(local view (render {:indicators [sample]} {:columns 10}))
(assert (= (text view) "test Alt-M") "value-only width included the hidden label")
(assert (= (. key-spans 1 :action) nil) "status mutated shared keybinding spans")
(assert (= (text (render {:indicators [{:label "◆" :fact {:type :text :value :test} :representation :icon}]} {:columns 6})) "◆ test"))
(assert (= (text (render {:indicators [{:label :model :fact {:type :text :value :test} :representation :label}]} {:columns 10})) "model test"))
;; The default header and input use no ornamental corner glyphs. Structural
;; borders in Markdown tables/code are independent and tested elsewhere.
(fn renderer [path id]
  (local setup ((. (fennel.dofile path) :setup) {}))
  (each [_ effect (ipairs setup.fx)]
    (when (= effect.id id) (lua "return effect.value.render")))
  (error (.. "missing component " id)))
(local header ((renderer :extensions/component/chrome.fnl :default.root.header)))
(assert (= (. header.lines 1 :spans 1 :text) :misa))
(local input-render (renderer :extensions/component/editor.fnl :default.editor.input))
(each [_ mode (ipairs [:insert :normal :visual])]
  (each [_ columns (ipairs [1 2 3 8 80])]
    (local text "one\ntwo\n世界")
    (each [_ cursor (ipairs [0 1 (length text)])]
      (local view (input-render {: text : cursor : mode} {: columns}))
      (each [_ line (ipairs view.lines)]
        (local rendered (table.concat (icollect [_ span (ipairs line.spans)] span.text)))
        (assert (not (rendered:find "┌" 1 true)))
        (assert (not (rendered:find "└" 1 true)))
        ;; The root clips a wide grapheme that cannot fit a tiny viewport;
        ;; this component's marker must itself fit the available columns.
        (assert (<= (misa.layout.width (. line.spans 1 :text)) columns)))
      (local cursor-line (. view.lines view.cursor.row))
      (local rendered (table.concat (icollect [_ span (ipairs cursor-line.spans)] span.text)))
      (assert (<= 0 view.cursor.byte (length rendered))))))
(local multiline (input-render {:text "one\ntwo" :mode :insert} {:columns 80}))
(each [_ line (ipairs multiline.lines)] (assert (= (. line.spans 1 :text) "│ ")))
(output "model affordance contracts passed\n")
