(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local context {:argv [] :config {:request_options {:enabled false}}})
(local one {:id :one :provider :test :model :one
            :api {:request_options {:enabled {:choices [false true] :default true}}}})
(local two {:id :two :provider :test :model :two
            :api {:request_options {:region {:choices [:west :east] :default :east}}}})
(set misa.models.all (fn [] [one two]))
;; Register the consumer first: startup and subsequent selections must use the
;; committed model, not depend on the ordering of extension registrations.
(local app ((require :tests.application) {:argv [] :config {}}))
(local declarations (require :misa.definitions))
(each [_ name (ipairs [:misa.json :misa.models.options :misa.models])]
  (local specs ((. (require name) :build) context))

  (app.define specs))
(var observed nil)
(app.define (declarations.build :model-startup-1 [{:catalog :events  :value {:event :test/read :handler (fn [db] (set observed db) nil)}}]))
(app.install context)
(fn dispatch [event]
  (local pending [event])
  (var at 1)
  (while (. pending at)
    (local effects (misa._dispatch (. pending at) {:columns 80 :lines 24 :interactive false}
                                  {:wall_ms 0 :monotonic_ms 0}))
    (misa._commit)
    (each [_ effect (ipairs effects)]
      (when (= effect.type :dispatch) (table.insert pending effect.event)))
    (set at (+ at 1))
    (assert (< at 100) "startup dispatch did not settle")))
(fn read-state [] (dispatch {:type :test/read}) observed)
(dispatch {:type :app/start})
(local initial (read-state))
(assert (= initial.models.selected :one))
(assert (= initial.request_options.model_id :one))
(assert (= initial.request_options.values.enabled false))
(dispatch {:type :model/select :id :two})
(local selected (read-state))
(assert (= selected.request_options.model_id :two))
(assert (= selected.request_options.values.region :east))
(assert (= selected.request_options.values.enabled nil))
(assert (= initial.request_options.model_id :one) "selection mutated previous state")
(dispatch {:type :models/provider-availability :provider :test :available false})
(local unavailable (read-state))
(assert (= unavailable.models.selected nil))
(assert (= unavailable.request_options.model_id nil))
(assert (= (next unavailable.request_options.values) nil))
(dispatch {:type :models/provider-availability :provider :test :available true})
(local restored (read-state))
(assert (= restored.request_options.model_id :one))
(assert (= restored.request_options.values.enabled false))
(output "model startup ordering contracts passed\n")
