(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local context {:argv [] :config {}})
(misa._setup (fennel.dofile :extensions/preferences.fnl) context)
(local original {:preferences {:clock 0 :scopes {:other {:entry {:favorite true :uses 0}}}}})
(local used (misa.preference_use original :commands :/model))
(assert (= original.preferences.clock 0) "use mutated its input")
(assert (= original.preferences.scopes.commands nil) "use inserted into its input")
(assert (= used.scopes.other original.preferences.scopes.other)
        "use copied unrelated scopes")
(assert (= used.clock 1))
(assert (= (. used.scopes.commands :/model :uses) 1))
(local again (misa.preference_use {:preferences used} :commands :/model))
(assert (= used.clock 1))
(assert (= (. used.scopes.commands :/model :uses) 1))
(assert (= again.clock 2))
(assert (= (. again.scopes.commands :/model :uses) 2))
(assert (= (. again.scopes.commands :/model :last) 2))
(output "preference state contracts passed\n")
