;; Startup policy belongs to the owning event handler, not global middleware.
(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {:config {}})

(each [_ persist (ipairs [false true])]
  (each [_ name (ipairs [:themes :components :animations])]
    (local config {: persist})
    (when (= name :components) (tset config :message :custom.message))
    (when (= name :animations) (tset config :roles {:status :default}))
    (local specs ((. (fennel.dofile (.. :extensions/ name :.fnl)) :setup)
                 {:config {name config}}))
    (var start nil)
    (each [_ spec (ipairs specs.fx)]
      (assert (not= spec.type :register/interceptor)
              "presentation startup must not install middleware")
      (when (and (= name :animations) (= spec.name :register/animation))
        (spec.handler {:id :default :value {:frames ["."]}}))
      (when (and (= spec.type :register/event) (= spec.name :app/start))
        (assert (not start) "startup must have a single owner handler")
        (set start spec.handler)))
    (assert start)
    (local untouched {:value :shared})
    (local db {: untouched})
    (local result (start db {:type :app/start}))
    (assert (= (. db name) nil) "startup mutated input")
    (local next-db (misa.patch db result.patch))
    (assert (= next-db.untouched untouched))
    (local initialized (. next-db name))
    (if (= name :components)
        (assert (= initialized.roles.message :custom.message))
        (assert (= initialized.active :default)))
    (when (= name :animations)
      (assert (= initialized.roles.status :default))
      (assert (= (next initialized.running) nil))
      (assert (= (next initialized.ticks) nil)))
    (assert (= (length (or result.fx [])) (if persist 1 0)))
    (when persist
      (assert (= (. result.fx 1 :type) :state/load))
      (assert (= (. result.fx 1 :completion) (.. name :/loaded))))
    (local before (misa.json.encode next-db))
    (local repeated (start next-db {:type :app/start}))
    (assert (= repeated.patch nil) "startup replaced existing selections")
    (assert (= before (misa.json.encode next-db)))
    (assert (= (misa.patch next-db (or repeated.patch {})) next-db))))
(output "presentation startup contracts passed\n")
