(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local app ((require :tests.application) {:argv [] :config {}}))
(local definitions (require :misa.definitions))
(local context {:argv [] :config {}})
(var observed nil)
(var next-value {:width 10})
(var fail false)
(app.define (definitions.build :fixture [{:catalog :events  :value {:event :inspect :handler (fn [_ _ cofx] (set observed cofx.presentation))}}
                          {:catalog :views :id :main :value (fn [_ cofx]
                                                          (assert cofx.projecting)
                                                          (misa.projections.publish :fixture next-value)
                                                          (when fail (error "failed frame"))
                                                          {:lines []})}]))
(app.install)
(local terminal {:columns 80 :lines 24})
(local clock {:wall_ms 0 :monotonic_ms 0})
(fn inspect [] (misa._dispatch {:type :inspect} terminal clock) (misa._commit) observed.fixture)
(assert (= (inspect) nil))
(misa._project terminal clock)
(misa._commit_projection)
(set next-value.width 20)
(assert (= (. (inspect) :width) 10) "publication retained mutable source")
(misa._project terminal clock)
(misa._rollback_projection)
(assert (= (. (inspect) :width) 10) "rejected frame published geometry")
(set fail true)
(assert (not (pcall misa._project terminal clock)))
(assert (= (. (inspect) :width) 10) "thrown projection published geometry")
(set fail false)
(misa._project terminal clock)
(misa._commit_projection)
(assert (= (. (inspect) :width) 20))
(set next-value nil)
(misa._project terminal clock)
(misa._commit_projection)
(assert (= (inspect) nil) "closed owner retained geometry")
(assert (not (pcall misa.projections.publish :outside {})))
(output "accepted presentation feedback passed\n")
