(local fennel (require :fennel))
(local output print)
(require :tests.application)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local application ((require :benchmarks.application) :native-transcript {:blocks 40}))
(local context {:config application.config :argv [] :host {:executable :misa}})
(local app ((require :tests.application) context))
(local definitions (require :tests.declarations))
(local counts {})
(each [id render (pairs application.definitions.views)]
  (tset application.definitions.views id (fn [db cofx]
                                          (local frame (render db cofx))
                                          (assert (not db.reject_frame) "reject speculative frame")
                                          frame)))
(each [id projection (pairs application.definitions.projections)]
  (local render projection.render)
  (set projection.render (fn [db context]
                           (tset counts id (+ (or (. counts id) 0) 1))
                           (render db context))))
(app.define application.definitions)
(app.define (definitions.collect :fixture [{:catalog :components :id :test.bad-editor :value {:render (fn [] (error "broken editor component"))}}
                          {:catalog :events  :value {:event :test/editor-component :handler (fn [_ event] {:patch {:components {:roles {:editor.input event.id}}}})}}
                          {:catalog :events  :value {:event :test/type :handler (fn [_ event] {:patch {:reject_frame (= event.reject true)
                                                          :editor {:text event.text :cursor (length event.text)}}})}}]))
(app.install)
(local terminal {:columns 100 :lines 32 :interactive true :images false})
(local clock {:wall_ms 0 :monotonic_ms 0})
(fn dispatch [event]
  (local queue [event])
  (var index 1)
  (while (<= index (length queue))
    (local effects (misa._dispatch (. queue index) terminal clock))
    (misa._commit)
    (each [_ effect (ipairs effects)]
      (when (= effect.type :dispatch) (table.insert queue effect.event)))
    (set index (+ index 1))))
(fn project []
  (local frame (misa._project terminal clock))
  (misa._commit_projection)
  frame)
(dispatch {:type :app/start})
(assert (= (next counts) nil) "model dispatch performed presentation work")
(project)
(local transcript-count (. counts :transcript.project))
(local input-count (. counts :editor.project-input))
(dispatch {:type :test/type :text "typing"})
(project)
(assert (= (. counts :transcript.project) transcript-count) "typing rebuilt the transcript")
(assert (= (. counts :editor.project-input) (+ input-count 1)))
(dispatch {:type :transcript/block-delta :response_id :bench :block_id "40" :text "stream"})
(project)
(assert (= (. counts :transcript.project) (+ transcript-count 1)))
(assert (= (. counts :editor.project-input) (+ input-count 1)) "streaming rebuilt editor input")
(dispatch {:type :messages/scroll :delta 3})
(project)
(assert (= (. counts :transcript.project) (+ transcript-count 1)) "scrolling rebuilt transcript content")
(local unchanged (misa.json.encode (project)))
(assert (= unchanged (misa.json.encode (project))))
(set terminal.columns 60)
(project)
(assert (= (. counts :transcript.project) (+ transcript-count 2)) "resize reused stale transcript layout")
(assert (= (. counts :editor.project-input) (+ input-count 2)))
(dispatch {:type :test/type :text "speculative" :reject true})
(assert (not (pcall misa._project terminal clock)))
(misa._rollback_projection)
(local after-rejection (. counts :editor.project-input))
(dispatch {:type :test/type :text "typing"})
(project)
(assert (= (. counts :editor.project-input) after-rejection) "rejected frame replaced accepted region cache")
(dispatch {:type :test/editor-component :id :test.bad-editor})
(local broken (project))
(assert (: (misa.json.encode broken) :find "Component editor.input failed" 1 true))
(assert broken.cursor "failed editor component broke root composition")
(dispatch {:type :test/editor-component :id :default.editor.input})
(assert (not (: (misa.json.encode (project)) :find "Component editor.input failed" 1 true)))
(output "projection region ownership passed")
