(local fennel (require :fennel))
(local output print)
(local file (assert (io.open :config/default.json :r)))
(local source (file:read :*a))
(file:close)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(local config (misa.json.decode source))
(set config.config.benchmark {:blocks 40})
(set config.config.models.default :bench/model)
(each [_ name (ipairs [:history :themes :components :preferences])]
  (tset config.config name (misa.patch (or (. config.config name) {}) {:persist false})))
(local context {:config config.config :argv [] :host {:executable :misa}})
(local counts {})
(misa._setup (fennel.dofile :benchmarks/native-transcript.fnl) context)
(each [_ name (ipairs config.extensions)]
  (when (and (not= name :json) (not= name :auth)
             (not (name:match "^provider%.")) (not (name:match "^protocol%.")))
    (local specs ((. (fennel.dofile (.. :extensions/ (name:gsub "%." "/") :.fnl)) :setup) context))
    (each [_ effect (ipairs (or specs.fx []))]
      (when (= effect.type :register/view)
        (local render effect.handler)
        (set effect.handler (fn [db cofx]
                              (local frame (render db cofx))
                              (assert (not db.reject_frame) "reject speculative frame")
                              frame)))
      (when (= effect.type :register/projection)
        (local render effect.render)
        (set effect.render (fn [db context]
                             (tset counts effect.name (+ (or (. counts effect.name) 0) 1))
                             (render db context)))))
    (misa._setup_effects specs)))
(misa._setup_effects {:fx [{:type :register/component :id :test.bad-editor
                           :value {:render (fn [] (error "broken editor component"))}}
                          {:type :register/event :name :test/editor-component
                           :handler (fn [_ event] {:patch {:components {:roles {:editor.input event.id}}}})}
                          {:type :register/event :name :test/type
                           :handler (fn [_ event] {:patch {:reject_frame (= event.reject true)
                                                          :editor {:text event.text :cursor (length event.text)}}})}]})
(misa._seal context)
(local terminal {:columns 100 :lines 32 :interactive true :images false})
(local clock {:wall_ms 0 :monotonic_ms 0})
(fn dispatch [event]
  (local queue [event])
  (var index 1)
  (while (<= index (length queue))
    (local effects (misa._dispatch (. queue index) terminal clock))
    (misa._commit)
    (each [_ effect (ipairs effects)]
      (when (= effect.type :dispatch) (table.insert queue effect.event)))
    (set index (+ index 1))))
(fn project []
  (local frame (misa._project terminal clock))
  (misa._commit_projection)
  frame)
(dispatch {:type :app/start})
(assert (= (next counts) nil) "model dispatch performed presentation work")
(project)
(local transcript-count counts.transcript_projection)
(local input-count counts.editor_input_projection)
(dispatch {:type :test/type :text "typing"})
(project)
(assert (= counts.transcript_projection transcript-count) "typing rebuilt the transcript")
(assert (= counts.editor_input_projection (+ input-count 1)))
(dispatch {:type :transcript/block-delta :response_id :bench :block_id "40" :text "stream"})
(project)
(assert (= counts.transcript_projection (+ transcript-count 1)))
(assert (= counts.editor_input_projection (+ input-count 1)) "streaming rebuilt editor input")
(dispatch {:type :messages/scroll :delta 3})
(project)
(assert (= counts.transcript_projection (+ transcript-count 1)) "scrolling rebuilt transcript content")
(local unchanged (misa.json.encode (project)))
(assert (= unchanged (misa.json.encode (project))))
(set terminal.columns 60)
(project)
(assert (= counts.transcript_projection (+ transcript-count 2)) "resize reused stale transcript layout")
(assert (= counts.editor_input_projection (+ input-count 2)))
(dispatch {:type :test/type :text "speculative" :reject true})
(assert (not (pcall misa._project terminal clock)))
(misa._rollback_projection)
(local after-rejection counts.editor_input_projection)
(dispatch {:type :test/type :text "typing"})
(project)
(assert (= counts.editor_input_projection after-rejection) "rejected frame replaced accepted region cache")
(dispatch {:type :test/editor-component :id :test.bad-editor})
(local broken (project))
(assert (: (misa.json.encode broken) :find "Component editor.input failed" 1 true))
(assert broken.cursor "failed editor component broke root composition")
(dispatch {:type :test/editor-component :id :default.editor.input})
(assert (not (: (misa.json.encode (project)) :find "Component editor.input failed" 1 true)))
(output "projection region ownership passed")
