(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local app ((require :tests.application) {:argv [] :config {}}))
(local declarations (require :tests.declarations))
(app.include (. (require :tests.stock) :misa.models.options) {:argv [] :config {}})
(app.install)
(local model {:id :one
              :api {:request_options {:enabled {:choices [false true]
                                               :default true}}}})
(local db {:models {:selected :one :entries [model]}
           :request_options {:configured {:enabled false} :values {}}})
(assert (= (misa.request-options.value db :enabled) false)
        "configured false was replaced by the default")
(assert (= db.request_options.model_id nil) "read initialized input state")
(assert (= db.request_options.values.enabled nil) "read mutated option values")
(local normal (misa.request-options.reconcile db))
(assert (= normal.model_id :one))
(assert (= normal.values.enabled false))
(local other {:id :two
              :api {:request_options {:region {:choices [:west :east]
                                               :default :west}}}})
(local normalized-other (misa.request-options.reconcile db other))
(assert (= normalized-other.model_id :two))
(assert (= normalized-other.values.region :west))
(assert (= normalized-other.values.enabled nil))
(local cleared (misa.request-options.reconcile {:request_options normal}))
(assert (= cleared.model_id nil))
(assert (= (next cleared.values) nil))
(assert (= normal.values.enabled false) "normalization changed earlier output")
(local fact (misa.sub db [:request-options/indicator :enabled]))
(assert (= fact.type :boolean))
(assert (= fact.value false) "indicator omitted configured false")
(assert (= fact (misa.sub (misa.patch db {:hover_action :other}) [:request-options/indicator :enabled])))
(assert (= (misa.sub db [:request-options/indicator :missing]) nil))
(local numeric (misa.patch db {:models {:entries (misa.replace
                                                 [{:id :one :api {:request_options {:count {:default 0}}}}])}}))
(assert (= (. (misa.sub numeric [:request-options/indicator :count]) :type) :number))
(assert (= (. (misa.sub numeric [:request-options/indicator :count]) :value) 0))
(assert (= db.request_options.values.enabled nil))
(output "request option state contracts passed\n")
