(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local context {:argv [] :config {}})
(local policies {})
(each [_ name (ipairs [:json :keybindings :actions :layout :commands :choices :choice_layout
                       :dialogs :picker :omnipicker :history])]
  (local specs ((. (fennel.dofile (.. :extensions/ name :.fnl)) :setup) context))
  (each [_ spec (ipairs specs.fx)]
    (when (= spec.type :register/interceptor)
      (tset policies spec.value.id spec.value.before)))
  (misa._setup_effects specs))
(misa._setup_effects {:fx [{:type :register/action
                          :value {:id :test.custom :label "Custom" :keys [:alt+z]
                                  :event {:type :custom :payload {:value 1}}
                                  :available (fn [db] db.allow_custom)}}]})
(local ids [:keybindings/normalize-alt :actions/input :dialogs/input
            :picker/input :omnipicker/global :history/input])
(local initial {:editor {:text "" :cursor 0 :mode :insert}})
(fn route [id db event]
  (local tx {: db : event :cofx {:terminal {:interactive true}} :fx [{:type :terminal/read}]})
  (local before (misa.json.encode tx))
  (local result ((. policies id) tx))
  (assert (= before (misa.json.encode tx)) (.. id " mutated input"))
  (assert (= result.db tx.db))
  (assert (= result.cofx tx.cofx))
  (assert (= result.fx tx.fx))
  (when (= result.event tx.event) (assert (= result tx)))
  result.event)
(local alt (route :keybindings/normalize-alt initial {:type :terminal/input :kind :alt :text :P :extra true}))
(assert (= alt.key :alt+p))
(assert (= alt.extra nil))
(assert (= (. (route :history/input initial {:type :terminal/input :kind :arrow_up}) :type)
           :history/previous))
(assert (= (. (route :actions/input initial {:type :terminal/input :kind :text :text ":find"}) :query)
           :find))
(local dialog-db (misa.patch initial {:dialog {:id :test}}))
(local picker-db (misa.patch initial {:picker {:id :test}}))
(local key {:type :terminal/input :kind :text :text :x :key :x :action :next})
(assert (= (route :actions/input dialog-db key) key))
(assert (= (route :history/input picker-db key) key))
(assert (= (. (route :dialogs/input dialog-db key) :type) :dialog/input))
(local picked (route :picker/input picker-db key))
(assert (= picked.type :picker/input))
(assert (= picked.action :next))
(assert (= picked.key :x))
(local palette-key {:type :terminal/input :kind :key :key :f1})
(assert (= (. (route :actions/input picker-db palette-key) :type) :actions/open))
(local omni-key {:type :terminal/input :kind :key :key :alt+/})
(assert (= (. (route :omnipicker/global initial omni-key) :type) :omnipicker/open))
(assert (= (route :omnipicker/global picker-db omni-key) omni-key))
(local custom-key {:type :terminal/input :kind :key :key :alt+z})
(assert (= (route :actions/input initial custom-key) custom-key))
(local custom (route :actions/input (misa.patch initial {:allow_custom true}) custom-key))
(assert (= custom.type :custom))
(assert (= custom.payload.value 1))
(local failure
       (G.for_all (G.tuple [(G.elements ids)
                            (G.elements [initial dialog-db picker-db
                                         (misa.patch initial {:selection {:id :test}})])
                            (G.elements [:terminal/input :unrelated])
                            (G.elements [:text :alt :key :arrow_up :arrow_down :escape :f1])
                            (G.elements [:x :P ":" "" "hello"])])
                  (fn [sample]
                    (route (. sample 1) (. sample 2)
                           {:type (. sample 3) :kind (. sample 4) :text (. sample 5)}))
                  {:cases 1000}))
(assert (not failure) (and failure (fennel.view failure)))
(output "routing transaction ownership passed\n")
