(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(each [_ name (ipairs [:json :layout :markdown :selection_document])]
  (misa._setup (fennel.dofile (.. :extensions/ name :.fnl)) {}))
(local specs ((. (fennel.dofile :extensions/selection.fnl) :setup)))
(local handlers {})
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler)))
(misa._setup_effects specs)
(local document {:id :doc :kind :document :label :doc :text "one two three"
                 :first 0 :last 13 :children []})
(misa._setup_effects {:fx [{:type :register/selection-source :id :test
                          :value (fn [db] (if db.empty [] (or db.documents [(or db.document document)])))}]})
(fn transition [db type action]
  (local before (misa.json.encode db))
  (local event {: type : action})
  (local result ((. handlers type) db event))
  (assert (= before (misa.json.encode db)) "selection mutated its input")
  (assert (not result.db))
  (values (misa.patch db (or result.patch {})) (or result.fx [])))
(fn opened [empty] (transition {: empty} :selection/open))
(fn act [db action] (transition db :selection/action action))
(local failure
       (G.for_all (G.vector (G.elements [:child :parent :previous :next :first :last
                                        :extend_next :extend_previous :visual :copy :ignore]))
                  (fn [actions]
                    (each [_ empty (ipairs [false true])]
                      (var db (opened empty))
                      (each [_ action (ipairs actions)]
                        (set db (act db action))
                        (local projection (misa.selection_projection db))
                        (when projection
                          (assert (<= 0 projection.first projection.last (length document.text)))))))
                  {:cases 500 :size 20}))
(assert (not failure) (and failure (fennel.view failure)))
;; Use explicit structural children to test range anchoring independently of parsing.
(local children [{:kind :word :label :one :first 0 :last 3}
                 {:kind :word :label :two :first 4 :last 7}
                 {:kind :word :label :three :first 8 :last 13}])
(local original-children misa.selection_children)
(set misa.selection_children (fn [] children))
(local leaf (act (opened false) :child))
(local selected (act (act leaf :visual) :next))
(local range (misa.selection_projection selected))
(assert (= range.first 0))
(assert (= range.last 7))
(local (_ effects) (act selected :copy))
(assert (= (. effects 2 :event :text) "one two"))
(local parent-selected (act selected :parent))
(assert (= (. (misa.selection_projection parent-selected) :last) 13))
(local visual-off (act selected :visual))
(assert (= (. (misa.selection_projection visual-off) :first) 4))
(assert (= (. (act selected :close) :selection) nil))
(set misa.selection_children original-children)
(set misa.theme_style (fn [] {:background :red}))
(local lines [{:source_start 0 :source_end 13 :spans [{:text document.text :source true :link :target}]}])
(local before (misa.json.encode lines))
(local decorated (misa.selection_decorate selected :doc document.text lines))
(assert (= before (misa.json.encode lines)) "highlighting mutated render input")
(assert (. decorated 1 :selected))
(assert (= (. decorated 1 :spans 1 :link) :target))
(misa._setup_effects {:fx [{:type :register/selection-action :id :custom
                          :value (fn [state] {:state (misa.patch state {:custom true})})}]})
(assert (. (act selected :custom) :selection :custom))
(each [_ newline (ipairs ["\n" "\r\n"])]
  (local text (table.concat ["- parent é" "  - nested 🙂" "    continued" "- sibling" "" "paragraph"] newline))
  (local tree (misa.selection_document :list :List text))
  (local list (. tree.children 1))
  (assert (= list.kind :list))
  (assert (= (length list.children) 2))
  (local parent (. list.children 1))
  (local nested (. parent.children 2))
  (assert (= nested.kind :list))
  (assert (= (length nested.children) 1))
  (assert (= (length (. nested.children 1 :children)) 2))
  (assert (= (text:sub (+ parent.first 1) parent.last)
             (table.concat ["- parent é" "  - nested 🙂" "    continued"] newline)))
  (assert (= (. tree.children 2 :kind) :paragraph))
  (local item (act (act (transition {:document tree} :selection/open) :child) :child))
  (local range-db (act (act item :visual) :next))
  (local selected-range (misa.selection_projection range-db))
  (assert (= selected-range.first list.first))
  (assert (= selected-range.last list.last))
  (local (_ copied) (act range-db :copy))
  (assert (= (. copied 2 :event :text) (text:sub (+ list.first 1) list.last)))
  (fn bounds [node]
    (each [_ child (ipairs node.children)]
      (assert (and (<= node.first child.first) (<= child.first child.last)
                   (<= child.last node.last)))
      (bounds child)))
  (bounds tree))
(local documents [(misa.selection_document :a :A "alpha\r\n\r\nomega")
                  (misa.selection_document :b :B "middle 🙂")
                  (misa.selection_document :c :C "last é")])
(local multi (transition {: documents} :selection/open))
(local backwards (act (act multi :visual) :previous))
(local slices (misa.selection_ranges backwards))
(assert (= (length slices) 2))
(assert (and (= (. slices 1 :id) :b) (= (. slices 2 :id) :c)))
(assert (= (misa.selection_projection backwards :a) nil))
(local (_ copied) (act backwards :copy))
(assert (= (. copied 2 :event :text) "middle 🙂\n\nlast é"))
(local all (act backwards :first))
(assert (= (length (misa.selection_ranges all)) 3))
(local (_ copied-all) (act all :copy))
(assert (= (. copied-all 2 :event :text) "alpha\r\n\r\nomega\n\nmiddle 🙂\n\nlast é"))
(local first-doc (act multi :first))
(local second-paragraph (act (act first-doc :child) :next))
(local partial-range (act (act (act second-paragraph :visual) :parent) :next))
(local partial-range-slices (misa.selection_ranges partial-range))
(assert (= (. partial-range-slices 1 :first) 9))
(local (_ copied-partial-range) (act partial-range :copy))
(assert (= (. copied-partial-range 2 :event :text) "omega\n\nmiddle 🙂"))
(local selected-b (misa.selection_projection partial-range :b))
(assert (and (= selected-b.first 0) (= selected-b.last (length "middle 🙂"))))
(local highlighted (misa.selection_decorate partial-range :b "middle 🙂"
                                           [{:spans [{:text "middle 🙂" :source true}]}]))
(assert (. highlighted 1 :selected) "nonfocused selected document was not highlighted")
(local frozen (misa.patch partial-range {:documents (misa.replace [])}))
(assert (= (misa.json.encode (misa.selection_ranges frozen))
           (misa.json.encode partial-range-slices)) "live document changes moved frozen selection")
(local reversed (act partial-range :previous))
(assert (= (length (misa.selection_ranges reversed)) 1))
(assert (= (length (misa.selection_ranges (act partial-range :visual))) 1))
(local multi-failure
       (G.for_all (G.vector (G.elements [:child :parent :previous :next :first :last
                                        :extend_next :extend_previous :visual :copy]))
                  (fn [actions]
                    (var state multi)
                    (each [_ action (ipairs actions)]
                      (set state (act state action))
                      (var previous-index 0)
                      (each [_ slice (ipairs (misa.selection_ranges state))]
                        (local index (. state.selection.indices slice.id))
                        (assert (> index previous-index) "range slices lost document order")
                        (assert (<= 0 slice.first slice.last (length slice.text))
                                "range escaped source bounds")
                        (set previous-index index))))
                  {:cases 200 :size 20}))
(assert (not multi-failure) (and multi-failure (fennel.view multi-failure)))
(output "selection state properties passed\n")
