(local fennel (require :fennel))
(local json-null {})
(local state ((fennel.dofile :src/lua_runtime/state.fnl) json-null))
(local old {:left {:value 1 :keep true} :right {:value 2} :items [1 2 3]})
(local updated (state.patch old {:left {:value 4} :items [9]}))
(assert (= updated.right old.right))
(assert (= updated.left.keep true))
(assert (= old.left.value 1))
(assert (= (length updated.items) 1))
(assert (= (. updated.items 1) 9))
(assert (= (state.patch old {}) old))
(assert (= (state.patch old {:left {} :items [1 2 3]}) old))
(assert (= (state.patch old {:left {:value 1}}) old))
(assert (= (state.patch old {:left (state.replace old.left)}) old))
(assert (= (state.patch old {:absent {:remove state.delete}}) old))
(local deleted (state.patch old {:left {:value state.delete}}))
(assert (= deleted.left.value nil))
(assert deleted.left.keep)
(assert (= deleted.right old.right))
(local replaced (state.patch old {:left (state.replace {}) :items (state.replace [])}))
(assert (= (next replaced.left) nil))
(assert (= (next replaced.items) nil))
(local cleared (state.patch old {:left state.delete}))
(assert (= cleared.left nil))
(local nullable (state.patch old {:left (state.replace nil)}))
(assert (= nullable.left nil))
(local nulled (state.patch old {:left json-null :enabled false}))
(assert (= nulled.left json-null))
(assert (= nulled.enabled false))
(assert (= (state.patch nulled {:left json-null :enabled false}) nulled))
(fn rejects [patch]
  (assert (not (pcall state.patch old patch)) "invalid patch was accepted")
  (assert (= old.left.value 1) "failed update changed original state"))
(rejects {:left {:value (fn [] nil)}})
(rejects {:left {:value (/ 0 0)}})
(rejects {:left (state.replace {:nested state.delete})})
(rejects {:left {[1] :one [3] :three}})
(rejects {:left {[1] :one :named :two}})
(local cycle {})
(set cycle.self cycle)
(rejects {:left cycle})
(rejects {:left (state.replace cycle)})
(rejects {:left (setmetatable {} {:__index old})})
(rejects [1 2])
(rejects state.delete)
(rejects (state.replace {}))
(local deep {})
(var cursor deep)
(for [_ 1 130]
  (set cursor.child {})
  (set cursor cursor.child))
(rejects deep)
(print "state patch contracts passed")
