(local fennel (require :fennel))
(local G (require :tests.generators))
(local registry ((fennel.dofile :src/lua_runtime/subscriptions.fnl)))
(registry.register {:id :path :read (fn [db q] (. db (. q 2)))})
(var computes 0)
(registry.register {:id :pair :inputs (fn [] [[:path :a] [:path :b]])
                    :compute (fn [inputs]
                               (set computes (+ computes 1))
                               (assert (= inputs.n 2))
                               {:a (. inputs 1) :b (. inputs 2)})})
(local scope (registry.scope 8))
(local first (scope.query {:a 1} [:pair]))
(assert (= (scope.query {:a 1 :other true} [:pair]) first))
(assert (= computes 1))
(local second (scope.query {:a 1 :b false} [:pair]))
(assert (= second.b false))
(assert (= computes 2))
(assert (not= (scope.query {:a 1} [:pair]) second) "trailing nil input was ignored")
(local original (scope.query {:a 1} [:pair]))
(local speculative (scope.fork))
(speculative.query {:a 99} [:pair])
(assert (= (scope.query {:a 1} [:pair]) original) "fork changed committed memoization")
(speculative.close)
(assert (not (pcall speculative.query {} [:pair])))
(registry.register {:id :cycle-a :inputs (fn [] [[:cycle-b]]) :compute (fn [] nil)})
(registry.register {:id :cycle-b :inputs (fn [] [[:cycle-a]]) :compute (fn [] nil)})
(assert (not (pcall scope.query {} [:cycle-a])))
(assert (= (scope.query {:a 1} [:pair]) original) "failed evaluation changed cache")
(registry.register {:id :fails :inputs (fn [] [[:path :a]]) :compute (fn [] (error :failed))})
(local size (scope.size))
(assert (not (pcall scope.query {:a 100} [:fails])))
(assert (= (scope.size) size))
(assert (= (scope.query {:a 1} [:pair]) original))
(for [i 1 100] (scope.query {} [:path (tostring i)]))
(assert (<= (scope.size) 8))
(scope.clear)
(assert (= (scope.size) 0))
(assert (= (registry.key [:path {:x 1 :y false}]) (registry.key [:path {:y false :x 1}])))
(assert (not= (registry.key [:path "a\31string\31b"]) (registry.key [:path :a :b])))
(assert (not= (registry.key [:path {:x 1}]) (registry.key [:path {:y 1}])))
(assert (not= (registry.key [:path 1]) (registry.key [:path "1"])))
(local cyclic [])
(tset cyclic 1 cyclic)
(assert (not (pcall registry.key [:path cyclic])))
(assert (not (pcall registry.key {1 :path 3 :hole})))
(assert (not (pcall registry.key [:path math.huge])))
(assert (not (pcall registry.register {:id :bad :read (fn []) :compute (fn [])})))
(local failure
       (G.for_all (G.vector (G.elements [false 0 1 :x "\31" "世界"]))
                  (fn [items]
                    (local q (icollect [_ item (ipairs items)] item))
                    (table.insert q 1 :path)
                    (local copy (icollect [_ item (ipairs q)] item))
                    (assert (= (registry.key q) (registry.key copy)))
                    (table.insert copy :extra)
                    (assert (not= (registry.key q) (registry.key copy))))
                  {:cases 1000 :size 20}))
(assert (not failure) (and failure (fennel.view failure)))
(print "subscription scope contracts passed")
