(local fennel (require :fennel))
(local G (require :tests.generators))
(local registry ((fennel.dofile :src/lua_runtime/subscriptions.fnl)))
(registry.register {:id :path :read (fn [db q] (. db (. q 2)))})
(var computes 0)
(registry.register {:id :pair :inputs [[:path :a] [:path :b]]
                    :compute (fn [inputs]
                               (set computes (+ computes 1))
                               (assert (= inputs.n 2))
                               {:a (. inputs 1) :b (. inputs 2)})})
(local scope (registry.scope 8))
(each [_ capacity (ipairs [false 0 -1 1.5 math.huge (- math.huge) :eight {}])]
  (assert (not (pcall registry.scope capacity)) "invalid capacity escaped the scope bound"))
(assert (not (pcall registry.scope (/ 0 0))))
(local first (scope.query {:a 1} [:pair]))
(assert (= (scope.query {:a 1 :other true} [:pair]) first))
(assert (= computes 1))
(local second (scope.query {:a 1 :b false} [:pair]))
(assert (= second.b false))
(assert (= computes 2))
(assert (not= (scope.query {:a 1} [:pair]) second) "trailing nil input was ignored")
(local original (scope.query {:a 1} [:pair]))
(local speculative (scope.fork))
(speculative.query {:a 99} [:pair])
(assert (= (scope.query {:a 1} [:pair]) original) "fork changed committed memoization")
(speculative.close)
(assert (not (pcall speculative.query {} [:pair])))
(registry.register {:id :cycle-a :inputs [[:cycle-b]] :compute (fn [] nil)})
(registry.register {:id :cycle-b :inputs (fn [] [[:cycle-a]]) :compute (fn [] nil)})
(assert (not (pcall scope.query {} [:cycle-a])))
(assert (= (scope.query {:a 1} [:pair]) original) "failed evaluation changed cache")
(registry.register {:id :fails :inputs (fn [] [[:path :a]]) :compute (fn [] (error :failed))})
(local size (scope.size))
(assert (not (pcall scope.query {:a 100} [:fails])))
(assert (= (scope.size) size))
(assert (= (scope.query {:a 1} [:pair]) original))
(for [i 1 100] (scope.query {} [:path (tostring i)]))
(assert (<= (scope.size) 8))
(scope.clear)
(assert (= (scope.size) 0))
(assert (= (registry.key [:path {:x 1 :y false}]) (registry.key [:path {:y false :x 1}])))
(assert (not= (registry.key [:path "a\31string\31b"]) (registry.key [:path :a :b])))
(assert (not= (registry.key [:path {:x 1}]) (registry.key [:path {:y 1}])))
(assert (not= (registry.key [:path 1]) (registry.key [:path "1"])))
(local cyclic [])
(tset cyclic 1 cyclic)
(assert (not (pcall registry.key [:path cyclic])))
(assert (not (pcall registry.key {1 :path 3 :hole})))
(assert (not (pcall registry.key [:path math.huge])))
(assert (not (pcall registry.register {:id :bad :read (fn []) :compute (fn [])})))
;; Static dependencies are validated at registration, including each query.
(each [_ inputs (ipairs [false :invalid {2 [:path :a]} [[]] [[:path math.huge]]])]
  (assert (not (pcall registry.register {:id :bad-static : inputs :compute (fn [])}))))
(assert (not (pcall registry.register {:id :bad-read :inputs [] :read (fn [])})))
(var constants 0)
(registry.register {:id :constant :inputs []
                    :compute (fn [inputs]
                               (assert (= inputs.n 0))
                               (set constants (+ constants 1))
                               {:answer 42})})
(local constant (scope.query {} [:constant]))
(assert (= constant (scope.query {:changed true} [:constant])))
(assert (= constants 1))
;; Scope mutation and recursive reads from callbacks cannot corrupt a consumer.
(each [_ operation (ipairs [:clear :close :fork])]
  (local id (.. :reentrant- operation))
  (registry.register {: id :inputs [] :compute (fn [] ((. scope operation)))})
  (local before (scope.size))
  (assert (not (pcall scope.query {} [id])))
  (assert (= before (scope.size)))
  (assert (= constant (scope.query {} [:constant]))))
(registry.register {:id :reentrant-query :read (fn [] (scope.query {} [:constant]))})
(assert (not (pcall scope.query {} [:reentrant-query])))
(registry.register {:id :depth :inputs (fn [q] [[:depth (+ (. q 2) 1)]]) :compute (fn [])})
(assert (not (pcall scope.query {} [:depth 0])))
(assert (= constant (scope.query {} [:constant])) "failed deep query poisoned the scope")
(var nested {})
(for [_ 1 128] (set nested {:child nested}))
(assert (not (pcall registry.key [:path nested])))
;; Inherited memoization is an internal fork detail, not a public scope argument.
(local external (registry.scope 1 {:injected {:used 1 :value :invalid}}))
(assert (= (external.size) 0))
;; Dynamic dependency declarations still receive the requested arguments.
(registry.register {:id :argument :inputs (fn [q] [[:path (. q 2)]])
                    :compute (fn [inputs q] {:key (. q 2) :value (. inputs 1)})})
(assert (= (. (scope.query {:a false} [:argument :a]) :value) false))
(assert (= (. (scope.query {:b 7} [:argument :b]) :value) 7))
(local failure
       (G.for_all (G.vector (G.elements [false 0 1 :x "\31" "世界"]))
                  (fn [items]
                    (local q (icollect [_ item (ipairs items)] item))
                    (table.insert q 1 :path)
                    (local copy (icollect [_ item (ipairs q)] item))
                    (assert (= (registry.key q) (registry.key copy)))
                    (table.insert copy :extra)
                    (assert (not= (registry.key q) (registry.key copy))))
                  {:cases 1000 :size 20}))
(assert (not failure) (and failure (fennel.view failure)))
(print "subscription scope contracts passed")
