(local fennel (require :fennel))
(local output io.write)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local app ((require :tests.application) {:argv [] :config {}}))
(local definitions (require :misa.definitions))
(local misa _G.misa)
(app.define ((. (fennel.dofile :extensions/misa/json.fnl) :build) {}))
(app.install)
(local specs ((. (fennel.dofile :extensions/misa/transcript/tools/summary.fnl) :build)))
(local handlers {})
(each [_ spec (pairs (. specs :events))]
  (tset handlers spec.event spec.handler))
(fn transition [db event]
  (local before (misa.json.encode db))
  (local result ((. handlers event.type) db event))
  (assert (= before (misa.json.encode db)) "summary controller mutated prior state")
  (values (misa.patch db (or (and result result.patch) {})) (or (and result result.fx) [])))
(local payload (string.rep "an observed tool finding\n" 30))
(local result {:type :transcript/tool-result :id :call :text payload})
(assert (= (misa.json.encode (transition {} result)) "{}"))
(set misa.models.for-role (fn [] {:id :model :provider :test :model :model}))
(local (queued queue-fx) (transition {} result))
(assert (= (length queued.tool_summary.queue) 1))
(assert (= (transition queued result) queued) "duplicate tool completion queued a second summary")
(local (started start-fx) (transition queued (. queue-fx 1 :event)))
(local request (. start-fx 1))
(assert (= request.type :provider.test))
(assert (= (length request.tools) 0))
(assert (= started.agent nil) "background summary created conversation state")
(assert (= (transition started {:type :agent/stream-delta :id :other :delta {:type :text :text :ignored}}) started))
(local streamed (transition started {:type :agent/stream-delta :id request.id :delta {:type :text :text "useful finding"}}))
(local used (transition streamed {:type :agent/stream-usage :id request.id :usage {:output_tokens 4}}))
(local (done done-fx) (transition used {:type :agent/stream-end :id request.id}))
(assert (= done.tool_summary.active nil))
(assert (= (. done-fx 1 :event :type) :tool-summary/usage))
(assert (= (. done-fx 1 :event :usage :output_tokens) 4))
(assert (= (. done-fx 2 :event :type) :transcript/tool-summary))
(assert (= (. done-fx 2 :event :id) :call))
(assert (= (. done-fx 2 :event :text) "useful finding"))
(assert (= (transition done {:type :agent/stream-end :id request.id}) done))
(local (reset reset-fx) (transition started {:type :agent/reset}))
(assert (= reset.tool_summary.active nil))
(assert (= (. reset-fx 1 :type) :operation/cancel))
(assert (= (transition reset {:type :agent/stream-end :id request.id}) reset))
(local (failed failed-fx) (transition started {:type :agent/stream-error :id request.id :message :failed}))
(assert (= failed.tool_summary.active nil))
(each [_ effect (ipairs failed-fx)] (assert (not= effect.event.type :transcript/tool-summary)))
(local (_ completed-fx) (transition started {:type :agent/result :id request.id :content [{:type :text :text :summary}]}))
(assert (= (. completed-fx 2 :event :text) :summary))
(assert (= (misa.json.encode (transition {} {:type :transcript/tool-result :id :error :text payload :is_error true})) "{}"))
(local waiting (transition started {:type :transcript/tool-result :id :second :text payload}))
(set misa.models.for-role (fn [] nil))
(local (unassigned cancelled-fx) (transition waiting {:type :tool-summary/reconcile}))
(assert (= unassigned.tool_summary.active nil))
(assert (= (length unassigned.tool_summary.queue) 0))
(assert (= (. cancelled-fx 1 :type) :operation/cancel))
(assert (= (. cancelled-fx 1 :id) request.id))
(assert (= (transition unassigned {:type :agent/stream-end :id request.id}) unassigned))
;; A provider may finish before the deferred role-change reconciliation runs.
(local (_ raced-fx) (transition streamed {:type :agent/stream-end :id request.id}))
(each [_ effect (ipairs raced-fx)] (assert (not= effect.event.type :transcript/tool-summary)))
(set misa.models.for-role (fn [] {:id :replacement :provider :test :model :replacement}))
(local (reassigned reassigned-fx) (transition waiting {:type :tool-summary/reconcile}))
(assert (= (length reassigned.tool_summary.queue) 2))
(assert (= (. reassigned.tool_summary.queue 1 :call_id) :call))
(local (restarted restart-fx) (transition reassigned {:type :tool-summary/next}))
(assert (not= restarted.tool_summary.active.id request.id))
(assert (= (. restart-fx 1 :model) :replacement))
(assert (= (transition restarted {:type :agent/stream-delta :id request.id :delta {:type :text :text :late}}) restarted))
(local reset-queued (transition queued {:type :agent/reset}))
(assert (= (transition reset-queued {:type :tool-summary/next}) reset-queued))
(local long-text (.. (string.rep "é" 150) "\n" (string.rep "é" 150) "\nthird line"))
(local (_ limited-fx) (transition restarted {:type :agent/result :id restarted.tool_summary.active.id
                                            :content [{:type :text :text long-text}]}))
(local limited (. limited-fx 2 :event :text))
(local (_ lines) (limited:gsub "\n" ""))
(assert (<= lines 2) "truncation added a fourth summary line")
(assert (not (limited:find "\195\n" 1 true)) "summary clipping split UTF-8")

;; Child accounting retains its canonical owner through role replacement.
(set misa.transcript {:blocks (fn [] [{:call_id :call :name :read_file :response_id :main-request}])})
(local linked (transition {} result))
(assert (= (. linked.tool_summary.queue 1 :parent_response_id) :main-request))
(local linked-start (transition linked {:type :tool-summary/next}))
(local (_ linked-fx) (transition linked-start {:type :agent/stream-end :id linked-start.tool_summary.active.id
                                              :usage {:output_tokens 4}}))
(assert (= (. linked-fx 1 :event :parent_response_id) :main-request))
(assert (= (. linked-fx 1 :event :call_id) :call))
(set misa.models.for-role (fn [] nil))
(local (_ linked-cancel) (transition linked-start {:type :tool-summary/reconcile}))
(assert (= (. linked-cancel 2 :event :parent_response_id) :main-request))
(output "tool summary lifecycle passed\n")
