(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(local specs ((. (fennel.dofile :extensions/messages.fnl) :setup) {:config {:messages {:max_string 12}}}))
(local handlers {})
(var register nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler))
  (when (= spec.name :register/transcript-delta) (set register spec.handler)))
(fn initial [kind]
  (local blocks [{:id :block :kind kind :streaming true :chunks [] :byte_count 0
                 :argument_chunks [] :argument_bytes 0}])
  {:messages {:blocks blocks :transcript blocks :by_response {:reply 1}
              :responses [{:id :reply :role :assistant :block_start 1 :block_count 1 :status :streaming
                           :started_monotonic_ms 100 :started_wall_ms 0}]}})
(fn transition [db fields]
  (local event (misa.patch fields {:type (or fields.type :transcript/block-delta) :response_id :reply :block_id :block}))
  (local before (misa.json.encode db))
  (local input (misa.json.encode event))
  (local result ((. handlers event.type) db event {:clock {:wall_ms 1000 :monotonic_ms 1100}
                                                 :terminal {:interactive true}}))
  (assert (= before (misa.json.encode db)) "delta mutated prior transcript")
  (assert (= input (misa.json.encode event)) "delta mutated provider event")
  (assert (not (and result result.db)))
  (local next (misa.patch db (or (and result result.patch) {})))
  (when (= event.type :transcript/block-delta)
    (assert (= next.messages.responses db.messages.responses)))
  (assert (= (misa.json.encode next.messages.blocks) (misa.json.encode next.messages.transcript)))
  next)
(local failure
       (G.for_all (G.vector (G.elements [{:text :hello} {:text ""} {:text "世界"}
                                         {:arguments_json "{}"} {:arguments_json_delta "long argument fragment"}
                                         {:arguments_json_delta :x} {:arguments {:token :secret :x 1}}]))
                  (fn [events]
                    (each [_ kind (ipairs [:assistant :thinking :tool_call])]
                      (var db (initial kind))
                      (each [_ event (ipairs events)] (set db (transition db event)))
                      (local block (. db.messages.blocks 1))
                      (when (not= kind :tool_call)
                        (assert (= block.byte_count (length (table.concat block.chunks)))))))
                  {:cases 500 :size 20}))
(assert (not failure) (and failure (fennel.view failure)))
(local text (initial :assistant))
(assert (= (transition text {:text ""}) text))
(local tool (initial :tool_call))
(local truncated (transition tool {:arguments_json_delta "abcdefghijklmnop"}))
(assert (. truncated.messages.blocks 1 :arguments_truncated))
(assert (= (transition truncated {:arguments_json_delta :ignored}) truncated))
(local replaced (transition truncated {:arguments_json "{}" :arguments_json_delta :ignored}))
(assert (= (. replaced.messages.blocks 1 :arguments_truncated) nil))
(assert (= (table.concat (. replaced.messages.blocks 1 :argument_chunks)) "{}"))
(local structured (transition tool {:arguments {:token :secret :x 1}}))
(assert (not= (. structured.messages.blocks 1 :arguments :token) :secret))
(register {:id :custom :value (fn [_ event] {:custom event.text})})
(assert (= (. (transition (initial :custom) {:text :value}) :messages :blocks 1 :custom) :value))
(local streamed (transition text {:text :hello}))
(local ended (transition streamed {:type :transcript/block-end}))
(assert (= (. ended.messages.blocks 1 :text) :hello))
(assert (= (. ended.messages.blocks 1 :chunks) nil))
(assert (= (. ended.messages.blocks 1 :streaming) false))
(local completed (transition streamed {:type :transcript/response-end :usage {:output_tokens 20}}))
(assert (= (. completed.messages.responses 1 :tokens_per_second) 20))
(assert (= (. completed.messages.responses 1 :metadata_block_id) :block))
(assert (= (. completed.messages.blocks 1 :text) :hello))
(local interrupted (transition streamed {:type :transcript/response-interrupted}))
(assert (. interrupted.messages.blocks 1 :interrupted))
(assert (= (. interrupted.messages.responses 1 :status) :interrupted))
(local final-tool (transition replaced {:type :transcript/block-end :arguments {:x 1} :name :tool :call_id :call}))
(assert (= (. final-tool.messages.blocks 1 :arguments :x) 1))
(assert (= (. final-tool.messages.blocks 1 :argument_chunks) nil))
(assert (= (. final-tool.messages.blocks 1 :argument_text) nil))
(local described (misa.patch tool {:messages {:blocks (misa.replace [{:id :block :kind :tool_call
                                                                    :streaming true :description :stale}])}}))
(local renamed (transition described {:type :transcript/block-end :name :missing}))
(assert (= (. renamed.messages.blocks 1 :description) nil) "renaming retained an old tool description")
(local finish-failure
       (G.for_all (G.tuple [(G.vector (G.elements [:a :b "世界" ""]))
                            (G.elements [:transcript/block-end :transcript/response-end :transcript/response-interrupted])])
                  (fn [sample]
                    (var db (initial :assistant))
                    (each [_ fragment (ipairs (. sample 1))] (set db (transition db {:text fragment})))
                    (local finished (transition db {:type (. sample 2)}))
                    (assert (= (. finished.messages.blocks 1 :text) (table.concat (. sample 1)))))
                  {:cases 500 :size 20}))
(assert (not finish-failure) (and finish-failure (fennel.view finish-failure)))
(output "transcript delta state properties passed\n")
