(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(local specs ((. (fennel.dofile :extensions/messages.fnl) :setup) {:config {}}))
(var (viewport scroll) nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.name :transcript_viewport) (set viewport spec.value))
  (when (= spec.name :messages/scroll) (set scroll spec.handler)))
(var projections 0)
(set misa.transcript_projection
     (fn [db]
       (set projections (+ projections 1))
       (icollect [index (ipairs db.rows)]
         {:spans [{:text (tostring index)}] :selected (= index db.selected_row)})))
(set misa.selection_projection (fn [db] db.selected))
(fn snapshot [count selected-row]
  {:messages {} :rows (fcollect [i 1 count] i) :selected_row selected-row
   :selected (when selected-row {:id :doc :first selected-row :last (+ selected-row 1)})})
(fn project [db room]
  (local before (misa.json.encode db))
  (local result (viewport db {:columns 80} room))
  (assert (= before (misa.json.encode db)))
  result)
(local original (snapshot 100))
(local expected (project original 10))
(assert (= expected.first 91))
(project (snapshot 200 12) 40)
(assert (= (misa.json.encode (project original 10)) (misa.json.encode expected))
        "a different speculative render changed the viewport")
(local selected (snapshot 100 12))
(assert (= (. (project selected 10) :first) 12))
(set misa.ui_regions (fn [db terminal] [{:id :transcript :viewport (project db (- terminal.lines 4))}]))
(fn move [db delta]
  (local before (misa.json.encode db))
  (local result (scroll db {: delta} {:terminal {:lines 14 :columns 80}}))
  (assert (= before (misa.json.encode db)))
  (misa.patch db (or result.patch {})))
(local moved (move selected -5))
(assert (= moved.messages.top 17))
(assert (= (. (project moved 10) :first) 17) "explicit scroll was overridden by selection")
(assert (= (. (project selected 10) :first) 12) "rollback retained a later scroll")
(local changed-selection (misa.patch moved {:selected_row 50 :selected {:first 50 :last 51}}))
(assert (= (. (project changed-selection 10) :first) 41))
(local tail (move original 5))
(assert (= tail.messages.top 86))
(assert (= (. (project (misa.patch tail {:rows (misa.replace (. (snapshot 150) :rows))}) 10) :first) 86))
(local failure
       (G.for_all (G.tuple [(G.elements [0 1 10 100]) (G.elements [0 1 10 40])])
                  (fn [sample]
                    (local count (. sample 1))
                    (local room (. sample 2))
                    (local db (snapshot count))
                    (local result (project db room))
                    (assert (<= (length result.lines) room))
                    (assert (>= result.first 1))
                    (project (snapshot 200 7) 3)
                    (assert (= (misa.json.encode result) (misa.json.encode (project db room)))))))
(assert (not failure) (and failure (fennel.view failure)))
(set projections 0)
(project original 10)
(assert (= projections 1) "viewport projected transcript more than once")
(set projections 0)
(move original 3)
(assert (= projections 1) "scroll measured the transcript more than once")
(local original-projection misa.transcript_projection)
(set misa.transcript_projection
     (fn [db]
       (local lines (original-projection db))
       (set (. lines 1 :selected) true)
       (set (. lines 1 :selection_id) :earlier-document)
       (set (. lines 12 :selection_id) :doc)
       lines))
(assert (= (. (project selected 10) :first) 12)
        "cross-document range revealed the anchor instead of the focused document")
(set misa.transcript_projection original-projection)
(output "transcript viewport contracts passed\n")
