(local fennel (require :fennel))
(local output io.write)
(local G (require :tests.generators))
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(misa._setup (fennel.dofile :extensions/json.fnl) {})
(local specs ((. (fennel.dofile :extensions/messages.fnl) :setup) {:config {:messages {:max_string 12}}}))
(local handlers {})
(var (register input-policy blocks-for) nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.type :register/event) (tset handlers spec.name spec.handler))
  (when (= spec.type :register/event-route) (set input-policy spec.value.resolve))
  (when (= spec.name :transcript_blocks) (set blocks-for spec.value))
  (when (= spec.type :register/sub) (misa._setup_effects {:fx [spec]}))
  (when (= spec.name :register/transcript-delta) (set register spec.handler)))
(local summary-fact (misa.sub {} [:messages/detail-indicator]))
(assert (= summary-fact.type :text))
(assert (= summary-fact.value :summary))
(assert (= summary-fact (misa.sub {:messages {:blocks []}} [:messages/detail-indicator])))
(assert (= (. (misa.sub {:messages {:verbose true}} [:messages/detail-indicator]) :value) :verbose))
(fn initial [kind]
  (local blocks [{:id :block :response_id :reply :kind kind :streaming true :chunks [] :byte_count 0
                 :argument_chunks [] :argument_bytes 0}])
  {:messages {:blocks blocks :next_id 0 :by_response {:reply 1}
              :responses [{:id :reply :role :assistant :block_start 1 :block_count 1 :status :streaming
                           :started_monotonic_ms 100 :started_wall_ms 0}]}})
(fn transition [db fields interactive]
  (local event (misa.patch fields {:type (or fields.type :transcript/block-delta) :response_id :reply :block_id :block}))
  (local before (misa.json.encode db))
  (local input (misa.json.encode event))
  (local result ((. handlers event.type) db event {:clock {:wall_ms 1000 :monotonic_ms 1100}
                                                 :terminal {:interactive (not= interactive false)}}))
  (assert (= before (misa.json.encode db)) "delta mutated prior transcript")
  (assert (= input (misa.json.encode event)) "delta mutated provider event")
  (assert (not (and result result.db)))
  (local next (misa.patch db (or (and result result.patch) {})))
  (when (= event.type :transcript/block-delta)
    (assert (= next.messages.responses db.messages.responses)))
  (assert (= next.messages.transcript nil) "transcript blocks were duplicated")
  (values next (or (and result result.fx) [])))
(local failure
       (G.for_all (G.vector (G.elements [{:text :hello} {:text ""} {:text "世界"}
                                         {:arguments_json "{}"} {:arguments_json_delta "long argument fragment"}
                                         {:arguments_json_delta :x} {:arguments {:token :secret :x 1}}]))
                  (fn [events]
                    (each [_ kind (ipairs [:assistant :thinking :tool_call])]
                      (var db (initial kind))
                      (each [_ event (ipairs events)] (set db (transition db event)))
                      (local block (. db.messages.blocks 1))
                      (when (not= kind :tool_call)
                        (assert (= block.byte_count (length (table.concat block.chunks)))))))
                  {:cases 500 :size 20}))
(assert (not failure) (and failure (fennel.view failure)))
(local text (initial :assistant))
(assert (= (transition text {:text ""}) text))
(local tool (initial :tool_call))
(local truncated (transition tool {:arguments_json_delta "abcdefghijklmnop"}))
(assert (. truncated.messages.blocks 1 :arguments_truncated))
(assert (= (transition truncated {:arguments_json_delta :ignored}) truncated))
(local replaced (transition truncated {:arguments_json "{}" :arguments_json_delta :ignored}))
(assert (= (. replaced.messages.blocks 1 :arguments_truncated) nil))
(assert (= (table.concat (. replaced.messages.blocks 1 :argument_chunks)) "{}"))
(local structured (transition tool {:arguments {:token :secret :x 1}}))
(assert (not= (. structured.messages.blocks 1 :arguments :token) :secret))
(register {:id :custom :value (fn [_ event] {:custom event.text})})
(assert (= (. (transition (initial :custom) {:text :value}) :messages :blocks 1 :custom) :value))
(local streamed (transition text {:text :hello}))
(local ended (transition streamed {:type :transcript/block-end}))
(assert (= (. ended.messages.blocks 1 :text) :hello))
(assert (= (. ended.messages.blocks 1 :chunks) nil))
(assert (= (. ended.messages.blocks 1 :streaming) false))
(local completed (transition streamed {:type :transcript/response-end :usage {:output_tokens 20}}))
(assert (= (. completed.messages.responses 1 :tokens_per_second) 20))
(assert (= (. completed.messages.responses 1 :metadata_block_id) :block))
(assert (= (. completed.messages.blocks 1 :text) :hello))
(local interrupted (transition streamed {:type :transcript/response-interrupted}))
(assert (. interrupted.messages.blocks 1 :interrupted))
(assert (= (. interrupted.messages.responses 1 :status) :interrupted))
(local final-tool (transition replaced {:type :transcript/block-end :arguments {:x 1} :name :tool :call_id :call}))
(assert (= (. final-tool.messages.blocks 1 :arguments :x) 1))
(assert (= (. final-tool.messages.blocks 1 :argument_chunks) nil))
(assert (= (. final-tool.messages.blocks 1 :argument_text) nil))
(local described (misa.patch tool {:messages {:blocks (misa.replace [{:id :block :kind :tool_call
                                                                    :streaming true :description :stale}])}}))
(local renamed (transition described {:type :transcript/block-end :name :missing}))
(assert (= (. renamed.messages.blocks 1 :description) nil) "renaming retained an old tool description")
(local finish-failure
       (G.for_all (G.tuple [(G.vector (G.elements [:a :b "世界" ""]))
                            (G.elements [:transcript/block-end :transcript/response-end :transcript/response-interrupted])])
                  (fn [sample]
                    (var db (initial :assistant))
                    (each [_ fragment (ipairs (. sample 1))] (set db (transition db {:text fragment})))
                    (local finished (transition db {:type (. sample 2)}))
                    (assert (= (. finished.messages.blocks 1 :text) (table.concat (. sample 1)))))
                  {:cases 500 :size 20}))
(assert (not finish-failure) (and finish-failure (fennel.view finish-failure)))
(local boot (transition {} {:type :app/start}))
(assert (= boot.messages.verbose false))
(local controls-failure
       (G.for_all (G.vector (G.elements [:messages/toggle-verbose :transcript/reset :messages/scroll]))
                  (fn [events]
                    (var db boot)
                    (var verbose false)
                    (each [_ type (ipairs events)]
                      (when (= type :messages/toggle-verbose) (set verbose (not verbose)))
                      (set db (transition db {: type :delta 3}))
                      (assert (= db.messages.verbose verbose))))
                  {:cases 500 :size 20}))
(assert (not controls-failure) (and controls-failure (fennel.view controls-failure)))
(local reset (transition (misa.patch streamed {:messages {:next_id 17 :top 5}}) {:type :transcript/reset}))
(assert (= reset.messages.next_id 17))
(assert (= reset.messages.top nil))
(assert (= (length reset.messages.blocks) 0))
(set misa.keybinding_action (fn [_ event] event.action))
(each [_ example (ipairs [{:kind :wheel_up :delta 3} {:kind :wheel_down :delta -3}
                          {:action :transcript_up :delta 12} {:action :transcript_down :delta -12}])]
  (local tx {:db boot :event {:type :terminal/input :kind example.kind :action example.action}
             :cofx {:terminal {:lines 24}}})
  (local before (misa.json.encode tx))
  (local next (input-policy tx.db tx.event tx.cofx))
  (assert (= before (misa.json.encode tx)) "transcript input policy mutated its transaction")
  (assert (= next.type :messages/scroll))
  (assert (= next.delta example.delta)))
(local response-started (transition boot {:type :transcript/response-start :role :assistant}))
(local block-started (transition response-started {:type :transcript/block-start :kind :assistant}))
(assert (= (. block-started.messages.responses 1 :block_count) 1))
(assert (= (. block-started.messages.blocks 1 :response_id) :reply))
(assert (= (. response-started.messages.responses 1 :block_count) 0))
(local complete-path (transition (transition block-started {:text :hello}) {:type :transcript/response-end}))
(assert (= (. complete-path.messages.blocks 1 :text) :hello))
(local creation-failure
       (G.for_all (G.vector (G.elements [:transcript/user :transcript/harness :transcript/tool-call
                                         :transcript/tool-result :transcript/assistant :transcript/reset]))
                  (fn [events]
                    (var db boot)
                    (each [_ type (ipairs events)]
                      (set db (transition db {: type :text :text :name :tool :id :call
                                             :content [{:type :text :text :assistant}]}))
                      (each [index owner (ipairs db.messages.responses)]
                        (assert (= (. db.messages.by_response owner.id) index))
                        (for [i owner.block_start (- (+ owner.block_start owner.block_count) 1)]
                          (assert (= (. db.messages.blocks i :response_id) owner.id))))))
                  {:cases 500 :size 20}))
(assert (not creation-failure) (and creation-failure (fennel.view creation-failure)))
(local called (transition boot {:type :transcript/tool-call :id :call :name :tool :arguments {:x 1}}))
(local returned (transition called {:type :transcript/tool-result :id :call :text :done}))
(assert (= (length returned.messages.blocks) 1))
(assert (= (. returned.messages.blocks 1 :result) :done))
(assert (= (. returned.messages.blocks 1 :status) :success))
(local interrupted-new (transition boot {:type :transcript/interrupted :request_id :new
                                         :content [{:type :text :text :partial}]}))
(assert (= (. interrupted-new.messages.responses 1 :status) :interrupted))
(assert (. interrupted-new.messages.blocks 1 :interrupted))

;; Notifications are scoped to canonical owners and appended after prior effects.
(fn notification [db event response-id block-id interactive]
  (local (next fx) (transition db event interactive))
  (local last (. fx (length fx)))
  (assert (= last.type :dispatch))
  (assert (= last.event.type :transcript/updated))
  (assert (= last.event.response_id response-id))
  (assert (= last.event.block_id block-id))
  (var count 0)
  (each [_ effect (ipairs fx)]
    (when (and (= effect.type :dispatch) (= effect.event.type :transcript/updated))
      (set count (+ count 1))))
  (assert (= count 1) "mutation emitted duplicate transcript notifications")
  (values next fx))
(notification response-started {:type :transcript/block-start :kind :assistant} :reply :block)
(notification text {:text :new} :reply :block)
(notification tool {:arguments_json_delta "{}"} :reply :block)
(notification streamed {:type :transcript/block-end} :reply :block)
(notification streamed {:type :transcript/response-end} :reply nil)
(notification streamed {:type :transcript/response-interrupted} :reply nil)
(notification called {:type :transcript/tool-result :id :call :text :done} :transcript-1 :transcript-1/1)
(each [_ type (ipairs [:transcript/user :transcript/harness :transcript/tool-call :transcript/tool-result])]
  (notification boot {: type :text :standalone :id :call} :transcript-1 :transcript-1/1))
(notification boot {:type :transcript/assistant :request_id :legacy
                    :content [{:type :text :text :first} {:type :thinking :text :second}]} :legacy nil)
(notification boot {:type :transcript/interrupted :request_id :legacy
                    :content [{:type :text :text :partial}]} :legacy nil)
(notification streamed {:type :transcript/interrupted :request_id :reply} :reply nil)
(each [_ sample (ipairs [[boot {:type :transcript/response-start}]
                         [text {:text ""}]
                         [truncated {:arguments_json_delta :ignored}]
                         [boot {:type :transcript/assistant :content []}]
                         [boot {:type :transcript/response-interrupted}]
                         [response-started {:type :transcript/response-end}]])]
  (local (_ fx) (transition (. sample 1) (. sample 2)))
  (assert (= (length fx) 0) "empty/no-op lifecycle emitted a notification"))
(local combined (transition streamed {:type :transcript/user :text :other}))
(local before-blocks (misa.json.encode combined))
(assert (= (blocks-for combined nil) combined.messages.blocks) "all-block lookup copied the canonical array")
(local reply-blocks (blocks-for combined :reply))
(assert (= (length reply-blocks) 1))
(assert (= (. reply-blocks 1) (. combined.messages.blocks 1)))
(assert (= (. (blocks-for combined :transcript-1 :transcript-1/1) 1) (. combined.messages.blocks 2)))
(assert (= (length (blocks-for combined :reply :transcript-1/1)) 0))
(assert (= (length (blocks-for combined :missing)) 0))
(assert (= (length (blocks-for {} :missing)) 0))
(assert (= (length (blocks-for {:messages {}} :missing)) 0))
(assert (= (length (blocks-for {} nil)) 0))
(assert (= before-blocks (misa.json.encode combined)))
(assert (= (. combined.messages.blocks 1) (. streamed.messages.blocks 1)) "standalone creation replaced another owner's block")
(local multiple (notification combined {:type :transcript/assistant :request_id :multiple
                                        :content [{:type :text :text :first}
                                                  {:type :thinking :text :second}]} :multiple nil))
(local matched (blocks-for multiple :multiple))
(assert (= (length matched) 2))
(assert (= (. matched 1) (. multiple.messages.blocks 3)))
(assert (= (. matched 2) (. multiple.messages.blocks 4)))
(local delta (notification multiple {:text :more} :reply :block))
(assert (= (. delta.messages.blocks 2) (. multiple.messages.blocks 2)))
(assert (= (. delta.messages.blocks 3) (. multiple.messages.blocks 3)))
(assert (= (. delta.messages.blocks 4) (. multiple.messages.blocks 4)))
(local finalized (notification multiple {:type :transcript/response-end} :reply nil))
(assert (= (. finalized.messages.blocks 3) (. multiple.messages.blocks 3)))
(local committed-lines [{:spans [{:text :committed}]}])
(set misa.render_component (fn [] {:lines committed-lines}))
(each [_ sample (ipairs [[boot {:type :transcript/user :text :user} :transcript-1 :transcript-1/1]
                         [boot {:type :transcript/harness :text :harness} :transcript-1 :transcript-1/1]
                         [boot {:type :transcript/assistant :request_id :legacy
                                :content [{:type :text :text :answer}]} :legacy]
                         [streamed {:type :transcript/response-end} :reply]])]
  (local (_ fx) (notification (. sample 1) (. sample 2) (. sample 3) (. sample 4) false))
  (assert (= (length fx) 2))
  (assert (= (. fx 1 :type) :view/commit))
  (assert (= (. fx 1 :lines) committed-lines)))
(set misa.render_component nil)
(var (project register-presentation) nil)
(each [_ spec (ipairs specs.fx)]
  (when (= spec.name :transcript_projection) (set project spec.value))
  (when (= spec.name :register/transcript-presentation) (set register-presentation spec.handler)))
(local cached {:lines [{:spans [{:text :cached}]}]})
(var rendered-role nil)
(var rendered-model nil)
(set misa.project_components (fn [_ _ items]
                              {:views (icollect [_ item (ipairs items)]
                                        (do (set rendered-role item.role)
                                            (set rendered-model item.model)
                                            cached))}))
(set misa.selection_decorate (fn [] [{:spans [{:text :decorated}]}]))
(set misa.selection_projection nil)
(set misa.syntax_projection nil)
(set misa.response_cost_projection nil)
(fn render [db]
  (local before (misa.json.encode db))
  (local cache-before (misa.json.encode cached))
  (local context {:columns 80})
  (local result (project db context))
  (assert (= before (misa.json.encode db)) "presentation mutated transcript facts")
  (assert (= cache-before (misa.json.encode cached)) "decoration mutated cached component output")
  (assert (= context.markdown nil) "presentation mutated render context")
  result)
(assert (= (. (render streamed) 1 :spans 1 :text) :decorated))
(assert (= rendered-role :transcript.assistant))
(assert (= rendered-model.rail :rail.assistant))
(local thinking (initial :thinking))
(render thinking)
(assert (= rendered-role :transcript.thinking))
(local collapsed (transition thinking {:type :transcript/block-end}))
(render collapsed)
(assert (= rendered-role :transcript.thinking_collapsed))
(render (misa.patch collapsed {:messages {:verbose true}}))
(assert (= rendered-role :transcript.thinking))
(render returned)
(assert (= rendered-model.detail :summary))
(assert (= rendered-model.result_detail :summary))
(set misa.selection_projection (fn [] {:id "12:transcript-1transcript-1/1" :text :selected :first 0 :last 8}))
(render returned)
(assert (= rendered-model.selection_source :result))
(assert (= rendered-model.result_detail :selected))
(register-presentation {:id :custom :value (fn [model]
                                            {:role :custom.render :model {:custom model.id}})})
(render (initial :custom))
(assert (= rendered-role :custom.render))
(assert (= rendered-model.custom :block))
(output "transcript delta state properties passed\n")
