;; Generate the catalog and service reference from the stock application.
;;
;; `sh tools/fennel tools/generate-docs.fnl` writes `docs/catalogs.md` and
;; `docs/services.md`. `--check` compares instead of writing, which is how the
;; suite notices a stale document.
(local fennel (require :fennel))
;; The framework removes io and print once it loads, so keep the file helpers
;; and the output function before installing anything.
(local write io.write)
(local open-file io.open)
(fennel.dofile :src/lua_runtime/framework.fnl)
(local misa _G.misa)
(local stock (require :misa.standard))
(misa._install stock.definitions {:argv [] :config stock.config})

(fn sorted [names]
  (table.sort names)
  names)

(fn add [lines items]
  (each [_ item (ipairs items)]
    (table.insert lines item))
  lines)

(fn kinds [definitions]
  (sorted (icollect [kind _ (pairs definitions)] kind)))

(fn ids [definitions kind]
  (sorted (icollect [id _ (pairs (or (. definitions kind) {}))]
            id)))

(fn describe [value]
  "Summarize an entry or service without dumping its implementation."
  (if (= (type value) :function)
      :function
      (= (type value) :table)
      (let [fields (sorted (icollect [key item (pairs value)]
                             (when (= (type key) :string) key)))]
        (if (= (length fields) 0) "{}" (.. "{" (table.concat fields " ") "}")))
      (tostring value)))

(fn catalog-overview [definitions]
  (local lines ["| Catalog | Entries |" "| --- | --- |"])
  (each [_ kind (ipairs (kinds definitions))]
    (table.insert lines
                  (.. "| `" kind "` | "
                      (tostring (length (ids definitions kind))) " |")))
  lines)

(fn event-detail [value]
  "Describe the event an entry handles, without printing a table address."
  (let [event value.event]
    (.. "event `" (if (= (type event) :table) (tostring (or event.type "?"))
                      (tostring event)) "`"
        (if (= (type value.priority) :number)
            (.. ", priority " (tostring value.priority))
            ""))))

(fn catalog-entries [definitions]
  (local lines [])
  (each [_ kind (ipairs (kinds definitions))]
    (add lines [(.. "### `" kind "`") "" "| ID | Shape |" "| --- | --- |"])
    (each [_ id (ipairs (ids definitions kind))]
      (let [value (. (. definitions kind) id)
            event (and (= (type value) :table) value.event)
            detail (if event (event-detail value) (describe value))]
        (table.insert lines (.. "| `" id "` | " detail " |"))))
    (table.insert lines ""))
  lines)

(fn service-paths []
  "Every installed service path, with what it holds."
  (local result [])

  (fn walk [prefix value]
    (local namespace?
           (and (= (type value) :table) (not= (next value) nil)
                (accumulate [ok true key item (pairs value) &until (not ok)]
                  (and (= (type key) :string)
                       (or (= (type item) :table) (= (type item) :function))))))
    (if namespace?
        (each [key item (pairs value)]
          (walk (.. prefix key ".") item))
        ;; The walk appends a separator per step; a leaf has no member path.
        (table.insert result [(prefix:sub 1 -2) value])))

  (each [namespace value (pairs misa)]
    (when (and (= (type value) :table) (not= (next value) nil))
      (walk (.. (tostring namespace) ".") value)))
  result)

(fn service-table []
  (local paths (service-paths))
  (table.sort paths (fn [left right]
                      (< (. left 1) (. right 1))))
  (local lines ["| Service | Holds |" "| --- | --- |"])
  (each [_ entry (ipairs paths)]
    (table.insert lines (.. "| `" (. entry 1) "` | " (describe (. entry 2))
                            " |")))
  lines)

(local catalogs
       (add [(.. "# Installed catalogs")
             ""
             "Generated by `tools/generate-docs.fnl` from the stock application."
             "Regenerate with `sh tools/fennel tools/generate-docs.fnl` after changing"
             "composition, and commit the result."
             ""
             "## Catalogs"
             ""]
            (add (catalog-overview stock.definitions)
                 (add ["" "## Entries" ""] (catalog-entries stock.definitions)))))

(local services (add [(.. "# Installed services")
                      ""
                      "Generated by `tools/generate-docs.fnl` after installing the stock"
                      "application. A service result is a borrowed immutable value unless its own"
                      "API documents otherwise. Members of a namespace are listed as separate"
                      "paths, so `misa.editor.layout` and `misa.editor.transition` both appear"
                      "under `editor`."
                      ""] (service-table)))

(local check? (= (. arg 1) :--check))
(local documents
       [[:docs/catalogs.md (table.concat catalogs "\n")]
        [:docs/services.md (table.concat services "\n")]])

(fn read-file [path]
  (with-open [file (open-file path :r)]
    (file:read :*a)))

(each [_ entry (ipairs documents)]
  (local path (. entry 1))
  (local body (. entry 2))
  (if check?
      (assert (= (read-file path) body)
              (.. path " is stale; run sh tools/fennel tools/generate-docs.fnl"))
      (with-open [file (assert (open-file path :w))]
        (file:write body))))

(write (if check? "generated documentation is current\n"
           "wrote docs/catalogs.md and docs/services.md\n"))
