(let [config {:choices {:purposes {:command-completion [:browse :favorites]}}}
      app ((require :tests.application) {: config})]
  (app.include (. (require :tests.stock) :misa.ui.values))
  (app.include (. (require :tests.stock) :misa.choices.matching))
  (app.include (. (require :tests.stock) :misa.keybindings))
  (app.include (. (require :tests.stock) :misa.ui.themes))
  (app.include (. (require :tests.stock) :misa.ui.themes.default))
  (app.include (. (require :tests.stock) :misa.ui.components))
  (app.include (. (require :tests.stock) :misa.ui.layout))
  (app.include (. (require :tests.stock) :misa.editor.render))
  (app.include (. (require :tests.stock) :misa.commands))
  (app.include (. (require :tests.stock) :misa.choices))
  (app.include (. (require :tests.stock) :misa.choices.preferences))
  (app.include (. (require :tests.stock) :misa.choices.preview))
  (app.include (. (require :tests.stock) :misa.choices.layout))
  (app.include (. (require :tests.stock) :misa.choices.picker))
  (app.include (. (require :tests.stock) :misa.commands.palette))
  (app.include (. (require :tests.stock) :misa.editor))
  (app.include (((. (require :fennel) :dofile) "@ROOT@/tests/command-history.fnl") {: config}))
  (app.include (. (require :tests.stock) :misa.models.preview))
  {: config :definitions app.definitions})
