(let [config {:choices {:purposes {:command-completion [:all]}}}
      app ((require :tests.application) {: config})]
  (app.include (. (require :tests.stock) :misa.ui.values))
  (app.include (. (require :tests.stock) :misa.choices.matching))
  (app.include (. (require :tests.stock) :misa.keybindings))
  (app.include (. (require :tests.stock) :misa.ui.themes))
  (app.include (. (require :tests.stock) :misa.ui.themes.default))
  (app.include (. (require :tests.stock) :misa.ui.components))
  (app.include (. (require :tests.stock) :misa.ui.layout))
  (app.include (. (require :tests.stock) :misa.markdown))
  (app.include (. (require :tests.stock) :misa.markdown.render))
  (app.include (. (require :tests.stock) :misa.ui.components.content))
  (app.include (. (require :tests.stock) :misa.ui.components.truncation))
  (app.include (. (require :tests.stock) :misa.transcript.tools))
  (app.include (. (require :tests.stock) :misa.transcript.tools.render))
  (app.include (. (require :tests.stock) :misa.ui.components.group))
  (app.include (. (require :tests.stock) :misa.transcript.render))
  (app.include (. (require :tests.stock) :misa.editor.render))
  (app.include (. (require :tests.stock) :misa.choices.picker.render))
  (app.include (. (require :tests.stock) :misa.ui.status.render))
  (app.include (. (require :tests.stock) :misa.ui.chrome))
  (app.include (. (require :tests.stock) :misa.commands))
  (app.include (. (require :tests.stock) :misa.choices))
  (app.include (. (require :tests.stock) :misa.choices.preview))
  (app.include (. (require :tests.stock) :misa.choices.layout))
  (app.include (. (require :tests.stock) :misa.choices.picker))
  (app.include (. (require :tests.stock) :misa.choices.picker.view))
  (app.include (. (require :tests.stock) :misa.editor))
  (app.include (. (require :tests.stock) :misa.ui))
  (app.include (((. (require :fennel) :dofile) "@ROOT@/tests/integration/fixtures/inline-choices.fnl") {: config}))
  (app.include (. (require :tests.stock) :misa.models.preview))
  (app.include (. (require :tests.stock) :misa.transcript.groups))
  (tset app.definitions.keybindings :choices/open_overlay
        {:context :choices :action :open_overlay :default [:alt+x]})
  (tset app.definitions.keybindings :choices/option_1_1
        {:context :choices :action :option_1_1 :default [:alt+z]})
  {: config :definitions app.definitions})
