(let [config {:components {:persist false}
              :themes {:persist false}
              :preferences {:persist false}}
      app ((require :tests.application) {: config})]
  (app.include (. (require :tests.stock) :misa.ui.values))
  (app.include (((. (require :fennel) :dofile) "@ROOT@/tests/interaction.fnl") {: config}))
  (app.include (. (require :tests.stock) :misa.json))
  (app.include (. (require :tests.stock) :misa.choices.matching))
  (app.include (. (require :tests.stock) :misa.keybindings))
  (app.include (. (require :tests.stock) :misa.actions))
  (app.include (. (require :tests.stock) :misa.clipboard))
  (app.include (. (require :tests.stock) :misa.dialogs))
  (app.include (. (require :tests.stock) :misa.commands))
  (app.include (. (require :tests.stock) :misa.choices))
  (app.include (. (require :tests.stock) :misa.choices.preferences))
  (app.include (. (require :tests.stock) :misa.ui.themes))
  (app.include (. (require :tests.stock) :misa.ui.themes.default))
  (app.include (. (require :tests.stock) :misa.ui.components))
  (app.include (. (require :tests.stock) :misa.ui.layout))
  (app.include (. (require :tests.stock) :misa.choices.preview))
  (app.include (. (require :tests.stock) :misa.choices.layout))
  (app.include (. (require :tests.stock) :misa.markdown))
  (app.include (. (require :tests.stock) :misa.selection.document))
  (app.include (. (require :tests.stock) :misa.selection))
  (app.include (. (require :tests.stock) :misa.markdown.render))
  (app.include (. (require :tests.stock) :misa.ui.components.truncation))
  (app.include (. (require :tests.stock) :misa.ui.components.group))
  (app.include (. (require :tests.stock) :misa.transcript.render))
  (app.include (. (require :tests.stock) :misa.editor.render))
  (app.include (. (require :tests.stock) :misa.choices.picker.render))
  (app.include (. (require :tests.stock) :misa.ui.status.render))
  (app.include (. (require :tests.stock) :misa.ui.chrome))
  (app.include (. (require :tests.stock) :misa.selection.render))
  (app.include (. (require :tests.stock) :misa.transcript))
  (app.include (. (require :tests.stock) :misa.choices.picker))
  (app.include (. (require :tests.stock) :misa.choices.picker.view))
  (app.include (. (require :tests.stock) :misa.commands.palette))
  (app.include (. (require :tests.stock) :misa.editor))
  (app.include (. (require :tests.stock) :misa.editor.editing))
  (app.include (. (require :tests.stock) :misa.ui))
  (app.include (. (require :tests.stock) :misa.models.preview))
  (app.include (. (require :tests.stock) :misa.transcript.groups))
  {: config :definitions app.definitions})
