(let [config {"models" {"default" "fake/default"}
              "providers" {"fake" {"responses" [{"stream" [{"type" "text"
                                                            "text" "partial"}]
                                                 "error" "stream interrupted"}]}}}
      app ((require :tests.application) {:config config})]
  (app.include (. (require :tests.stock) :misa.agent.stream))
  (app.include (. (require :tests.stock) :misa.keybindings))
  (app.include (. (require :tests.stock) :misa.ui.values))
  (app.include (. (require :tests.stock) :misa.providers.fake))
  (app.include (. (require :tests.stock) :misa.ui.themes))
  (app.include (. (require :tests.stock) :misa.ui.themes.default))
  (app.include (. (require :tests.stock) :misa.ui.components))
  (app.include (. (require :tests.stock) :misa.ui.layout))
  (app.include (. (require :tests.stock) :misa.markdown))
  (app.include (. (require :tests.stock) :misa.markdown.render))
  (app.include (. (require :tests.stock) :misa.ui.components.content))
  (app.include (. (require :tests.stock) :misa.ui.components.truncation))
  (app.include (. (require :tests.stock) :misa.transcript.tools))
  (app.include (. (require :tests.stock) :misa.transcript.tools.render))
  (app.include (. (require :tests.stock) :misa.ui.components.group))
  (app.include (. (require :tests.stock) :misa.transcript.render))
  (app.include (. (require :tests.stock) :misa.editor.render))
  (app.include (. (require :tests.stock) :misa.choices.picker.render))
  (app.include (. (require :tests.stock) :misa.ui.status.render))
  (app.include (. (require :tests.stock) :misa.ui.chrome))
  (app.include (. (require :tests.stock) :misa.transcript))
  (app.include (. (require :tests.stock) :misa.models))
  (app.include (. (require :tests.stock) :misa.agent))
  (app.include (. (require :tests.stock) :misa.commands))
  (app.include (. (require :tests.stock) :misa.choices))
  (app.include (. (require :tests.stock) :misa.editor))
  (app.include (. (require :tests.stock) :misa.ui))
  (app.include (((. (require :fennel) :dofile) "@ROOT@/tests/integration/fixtures/interrupted-check.fnl") {:config config}))
  (app.include (. (require :tests.stock) :misa.transcript.groups))
  {:config config :definitions app.definitions})
