(let [config {}
      app ((require :tests.application) {:config config})]
  (app.include (. (require :tests.stock) :misa.ui.values))
  (app.include (. (require :tests.stock) :misa.keybindings))
  (app.include (. (require :tests.stock) :misa.dialogs))
  (app.include (. (require :tests.stock) :misa.ui.themes))
  (app.include (. (require :tests.stock) :misa.ui.themes.default))
  (app.include (. (require :tests.stock) :misa.ui.components))
  (app.include (. (require :tests.stock) :misa.ui.layout))
  (app.include (. (require :tests.stock) :misa.markdown))
  (app.include (. (require :tests.stock) :misa.markdown.render))
  (app.include (. (require :tests.stock) :misa.ui.components.truncation))
  (app.include (. (require :tests.stock) :misa.ui.components.group))
  (app.include (. (require :tests.stock) :misa.transcript.render))
  (app.include (. (require :tests.stock) :misa.editor.render))
  (app.include (. (require :tests.stock) :misa.ui.components.buttons))
  (app.include (. (require :tests.stock) :misa.dialogs.render))
  (app.include (((. (require :fennel) :dofile) "@ROOT@/tests/presentation.fnl") {:config config}))
  (app.include (. (require :tests.stock) :misa.transcript.groups))
  {:config config :definitions app.definitions})
