(let [config {"messages" {"verbose" true}}
      app ((require :tests.application) {:config config})]
  (app.include (. (require :tests.stock) :misa.ui.values))
  (app.include (. (require :tests.stock) :misa.ui.themes))
  (app.include (. (require :tests.stock) :misa.ui.themes.default))
  (app.include (. (require :tests.stock) :misa.ui.components))
  (app.include (. (require :tests.stock) :misa.ui.layout))
  (app.include (. (require :tests.stock) :misa.markdown))
  (app.include (. (require :tests.stock) :misa.markdown.render))
  (app.include (. (require :tests.stock) :misa.ui.components.content))
  (app.include (. (require :tests.stock) :misa.ui.components.truncation))
  (app.include (. (require :tests.stock) :misa.transcript.tools))
  (app.include (. (require :tests.stock) :misa.transcript.tools.render))
  (app.include (. (require :tests.stock) :misa.ui.components.group))
  (app.include (. (require :tests.stock) :misa.transcript.render))
  (app.include (. (require :tests.stock) :misa.costs))
  (app.include (. (require :tests.stock) :misa.transcript))
  (app.include (((. (require :fennel) :dofile) "@ROOT@/tests/integration/fixtures/response-metadata.fnl") {:config config}))
  (app.include (. (require :tests.stock) :misa.transcript.groups))
  {:config config :definitions app.definitions})
